### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by devstude** [connext/community-sybil-reports#411] opened 2023-08-26 20:41 UTC
# Related Addresses
0xa382f0f47c6399f6275725866debd009200e8977
0x69d23d82335aa5d7f42e9b0313ae7d634784c185
0xf1a9a77f96cf25c21b7473b0d244d62edb18259b
0x0e65b12deeec01b674ed961ded3edc699fd00f33
0x42a1e744cb7669f484c6ceb2e1fe8a4e60850b91
0x2815b25134f22d7c8deba56cc1fd388dd19a6fcf
0xd86f877d7df0c1afc193323d798287edca1d37c8
0x531118d663b4f193f0347aec30541b59263a57b1
0xda042fa318bad4fea4fa0cbcec8a5d672e48b3ea
0x2093b9f3d8cd00cacfe9c66755268dbb75d42d40

# Reasoning

All addresses where initially funded on BNB Chain from same main account 0x9743a924b33c0102bb27e2cd946f915e6ade8315 (which is not eligible for the Connext airdrop) with the same amount of 0,36 bnb at the same day 2021-05-27: owner spent just 2 minutes to spread funds on all those accounts.

Initial   funding to | Funded From | Time | Value, eth
-- | -- | -- | --
0xf8000a68965cfff154ebbc771e790752bc10ab1d | 0x9743a924b33c0102bb27e2cd946f915e6ade8315 | 2021-05-27 12:40:38 UTC | 0,36
0x575929268e30cb510cf4718becfc088a2c90fe60 | 0x9743a924b33c0102bb27e2cd946f915e6ade8315 | 2021-05-27 12:40:59 UTC | 0,36
0xc33faff1b8e89c5a4f1b320ca1f95b394f52cb21 | 0x9743a924b33c0102bb27e2cd946f915e6ade8315 | 2021-05-27 12:41:11 UTC | 0,36
0x914c25210b11be6480e2032aaf02a025068a804d | 0x9743a924b33c0102bb27e2cd946f915e6ade8315 | 2021-05-27 12:41:35 UTC | 0,36
0xa7943fe31025d7bca1650b5e4dd670b89165f05a | 0x9743a924b33c0102bb27e2cd946f915e6ade8315 | 2021-05-27 12:41:50 UTC | 0,36
0xc76a59bc8ad338dbb8e1374cfead81f142c52a53 | 0x9743a924b33c0102bb27e2cd946f915e6ade8315 | 2021-05-27 12:42:11 UTC | 0,36
0x990afd36872f80a469c12fbf1bcd29005209ee7d | 0x9743a924b33c0102bb27e2cd946f915e6ade8315 | 2021-05-27 12:42:23 UTC | 0,36
0x64463d05904e09cde530894b33590f5708dc2811 | 0x9743a924b33c0102bb27e2cd946f915e6ade8315 | 2021-05-27 12:42:35 UTC | 0,36
0xe3d0c2b91c5166a5ec281d235493217593c241bf | 0x9743a924b33c0102bb27e2cd946f915e6ade8315 | 2021-05-27 12:42:50 UTC | 0,36
0xba6c3326349002cfa03539287fb0a2f347d853a5 | 0x9743a924b33c0102bb27e2cd946f915e6ade8315 | 2021-05-27 12:43:02 UTC | 0,36

All those accounts have a lot of similar blockchain activity on different chains.

# Methodology

Those accounts where found by running dune scripts that analyze initial wallet fundings (for wallets eligible for the Connext user airdrop) and manual checking of same time/value/initial funder wallets. 

# Rewards Address

0xEd3aAD546d663084794CcCcA6987089395FC1760

**Comment by Stakeridoo** [comment] 2023-09-02 17:54
Duplicate of #410

**Closed** 2023-09-03 15:41 UTC
Labels: duplicate
