### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by capposa** [connext/community-sybil-reports#199] opened 2023-08-25 13:50 UTC
# Related Addresses
1 person
0x087FC4F8004395Fc8C6FdAD436aC48D56C779F87
0x983f87acc5d33F810913F6b1153a4a1c3EC93e5D
0x673908D2707456ADa64D1Cc8fff15879B46703ac
2 person
0x1690C3435802CA8482F76ecFc32158b345057649
0xD08267cE370BE8074FcA61f2ee855C78b0AB910D
0xB18Af22479F14F26487Aa6354dAD7D7CBcd527F1
0x470169600E08c6733cBAfeeEdeF1352f4738B0C7
0xc5263403C4B068e0efaFa3463e08e40F8aDe391C
0xE6d36Da02583C1acD79FFC7065f6d9BB1e8a6C30
0x3d4f2F2feb4963BdCC0cd48d6e2B57806c3F2ff3
0x00493ba4E1864aCd75e2d76D7B6F4E6593615631
0x0715B21A1f43C80CE41daCb7E1Ea89Aa8fe3FC2A
0x5dF9576b0C6441F69809Ca510685C01F09DbA1e9
0xF0a9dA8cc27830D4a7Cc9Da49a18655371653321
0x2C382DAe1a94D689BEcf78eDBEB1900C46f75ca2
0xC218E61C2f6EDe9bfdb504f85BDf8802CBEce31A
0x1eA05E66559c497b7d786a3F657BaA5ba7FE0Bc3
0x63ea96398ffCaC3b4BEdE15DE824468328E3BC45
0xCB8189bcF385867Db54E72c390472D646A448003
0xec911027C5956C4B7e3b79B06c0D107b3a003F1F
0x53716f7fF7949e06AfaEED5aA169cA31E53d7d46
0xaac2F9d9D26c7CDD9b8d2cca67a08323E525F641
0xDfE9e837A7BC21b0c928066e471E542fF75d3831
0xA2D8425A38fAD12058519c0d334d89172AE42D2c
0x552F386a3C6fda19eB75AcdE84f013dF69a7006e
0x71254Be0AF9f5522425C75A2dD1C0fC42162655F
0x0A26c375EE357dfB67441871dDec53f57FFE6d65
0x503d17563769a941f9c877966790C389053F79A1
0x1f27F86dBB71F47222ccb50F8A19acE82cDf29b4
0x9542495bBE11840eB64287f73aC78DA61C837714
0xC2B1FAA0a2615C6e315596dc6CbE3c1049C0aA0F
0x1d9D739004473c231cd08111bB5dd5E7c082dCd4
3 person
0x8eF9E131Dc534Cf385F93E57a4BAb2dE4Bc349b3
0x0F5e3217961658e0f13a97a43B867d702E0A90A2
0xaD974c32442C77118EA96971aEec54b33d53f5eb
0xE5AF89D2A2Ecd9Fc511638DA53484DfF9340521c
0xf07FCA33EA8b436d2665e15D3Bd16ae5D3A295D7
0xfa5f2CB9D70f50D43c707E740C16603eF10df17F
4 person
0xEcA3d118aB1dA6952a538D2ce78f12f08917eb39
0xf7Dd5E140DDc843deA9857cd2B6bB7D16d5a6094
5 person
0x53A60AC4f0f3758731d41e5a13aE38Db48B7Bb40
0x0d2DcFb901C476AEb9105e38A7b7b451FD109A92
0x7c950FDE7dD26Fe40896d93B8Fb7532B8ce5C45D
0xF916719c7251e109Cf3D1a977B6CAD198b630C32

# Reasoning
1 person addresses received funding form the same parent address 0x1ce6E8a1AE0ddb51cBB407510AbBb57207c6b5aa.
2 person addresses received funding from the same parent address 0x0161eb3bE364eaBBbcf5C8E59A3A989AB03E77d5. After funding, each transferred funds from Arbitrum to Optimism between 12:50 UTC and 13:30 UTC on may 23rd. On May 23st in the same window and sequence, the accounts sent funds from Optimism to Arbitrum. On may 26st in the same window and sequence, the accounts sent funds from Arbitrum to Optimism between 7:50 UTC and 8:20 UTC.
3 person addresses received funding from each other. arvinra.eth and العربی.eth transferred funds from Polygon between 19:45 and 20:05 on june 23rd, 11-sep.eth and vshesan1.eth transferred funds from Polygon between 12:15 and 12:45.
4 person addresses received funding form the same parent address 0xA1f16F4724685f7411eC31E76455D4776deED4aC. 
After funding, each transferred funds from Arbitrum to ConnextDiamond between 21:10 UTC and 21:35 UTC on May 15th.
5 person addresses received funding from the same parent address 0xF916719c7251e109Cf3D1a977B6CAD198b630C32. After funding, each transferred funds from Arbitrum to ConnextDiamond between 19:55 UTC and 20:15 UTC on May 20th.

# Methodology
The reported addresses were discovered by checking in the number of bridge transactions made via Akrham. The resulting addresses were analyzed to find repeating transfers at standard intervals and sequence.

p1 https://platform.arkhamintelligence.com/explorer/address/0x0161eb3bE364eaBBbcf5C8E59A3A989AB03E77d5
p2 https://platform.arkhamintelligence.com/explorer/address/0x1ce6E8a1AE0ddb51cBB407510AbBb57207c6b5aa
p3 https://platform.arkhamintelligence.com/explorer/address/0x8eF9E131Dc534Cf385F93E57a4BAb2dE4Bc349b3
p4 https://platform.arkhamintelligence.com/explorer/address/0xEcA3d118aB1dA6952a538D2ce78f12f08917eb39
p5 
![image](https://github.com/connext/community-sybil-reports/assets/133208111/fd397c37-b5c8-4167-8b45-0de1a0ec4dca)
![image](https://github.com/connext/community-sybil-reports/assets/133208111/98c8ff71-814d-430f-8ccb-fff350a09a26)
![image](https://github.com/connext/community-sybil-reports/assets/133208111/5b5e717c-326b-4d61-9b21-af1e7ddce72a)
![image](https://github.com/connext/community-sybil-reports/assets/133208111/2594472a-437f-4207-ae53-369dd1d4ac0d)
![image](https://github.com/connext/community-sybil-reports/assets/133208111/959ff13f-a097-440a-9dd8-58993b697d16)

# Rewards Address
0x83c249D8974adBDe4Bf7a908aa57b8dA4AB804A5

**Comment by ArjunBhuptani** [comment] 2023-09-01 01:21
2nd person is duplicate of #12

**Closed** 2023-09-02 18:04 UTC
Labels: duplicate
