### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by givemeasigh89** [connext/community-sybil-reports#70] opened 2023-08-25 06:40 UTC
# Related Addresses
```
0xc2b1faa0a2615c6e315596dc6cbe3c1049c0aa0f
0x503d17563769a941f9c877966790c389053f79a1
0x0a26c375ee357dfb67441871ddec53f57ffe6d65
0x1d9d739004473c231cd08111bb5dd5e7c082dcd4
0xec911027c5956c4b7e3b79b06c0d107b3a003f1f
0x71254be0af9f5522425c75a2dd1c0fc42162655f
0x552f386a3c6fda19eb75acde84f013df69a7006e
0xa2d8425a38fad12058519c0d334d89172ae42d2c
0xdfe9e837a7bc21b0c928066e471e542ff75d3831
0x1ea05e66559c497b7d786a3f657baa5ba7fe0bc3
0x53716f7ff7949e06afaeed5aa169ca31e53d7d46
0x1f27f86dbb71f47222ccb50f8a19ace82cdf29b4
0xc218e61c2f6ede9bfdb504f85bdf8802cbece31a
0x63ea96398ffcac3b4bede15de824468328e3bc45
0x2c382dae1a94d689becf78edbeb1900c46f75ca2
0xf0a9da8cc27830d4a7cc9da49a18655371653321
0xe6d36da02583c1acd79ffc7065f6d9bb1e8a6c30
0xcb8189bcf385867db54e72c390472d646a448003
0x470169600e08c6733cbafeeedef1352f4738b0c7
0x5df9576b0c6441f69809ca510685c01f09dba1e9
0x1690c3435802ca8482f76ecfc32158b345057649
0x0715b21a1f43c80ce41dacb7e1ea89aa8fe3fc2a
0x00493ba4e1864acd75e2d76d7b6f4e6593615631
0x3d4f2f2feb4963bdcc0cd48d6e2b57806c3f2ff3
0xb18af22479f14f26487aa6354dad7d7cbcd527f1
0xc5263403c4b068e0efafa3463e08e40f8ade391c
```
# Reasoning

All wallets were created 143 days ago and have the same lifetime. All wallets have approximately the same value on their balance at the moment, 470-490$. 
The value of assets in the Gnosis network is EXACTLY 196$ FOR ALL wallets, part of which is in the Gnosis connection pool. 
All wallets at the time of the Connext LP#2 promotion had an average balance of approximately $6800 and the current balance was around $13600, a few dollars difference!
All wallets deposited money at the same time, the difference is in minutes. If you look at the average time of holding money in pools, it will differ by minutes!
After the promotion ended, all funds from these wallets  were withdrawn to the address 0x0161eb3be364eabbbcf5c8e59a3a989ab03e77d5, to the arbitrum network, we can simply check through arbiscan.io -
https://arbiscan.io/address/0x0161eb3be364eabbbcf5c8e59a3a989ab03e77d5#tokentxns
Here you can see all our addresses that sent money to the same address after the end of the promotion at Jun-26-2023 ~10 AM +UTC! 
![proof2](https://github.com/connext/community-sybil-reports/assets/108975905/0ea8c092-31a1-4cb6-92bb-1be534edb3ac)

The amount of transactions is equal to the funds that were in the connect pools of the Arbitrum network - ~13,600 USDT.

# Methodology
At the time of the ConnectLP 2 promotion for DAI and USDT, I monitored the addresses that took part and claimed the top 30% for USDT in the arbiter network. At some point, I used dune for this and found strange activity, more than 20 addresses appeared, with the same average USDT, as well as an almost identical balance and lifetime in the pool.
Further, I closely watched whether the money would be withdrawn from there and to what address, after the end or before the end of the connect promotion.
As a result, all funds were withdrawn at about the same time from the pools, and at the same time to the same address 0x0161eb3be364eabbbcf5c8e59a3a989ab03e77d5
I used parameters like day-life time wallet, current assets balance, dune.com, debank.com and arbiscan.io for monitroing trx.

links:
https://dune.com/sdraste/connext-campaign-usdt-dai
second page
https://arbiscan.io/address/0x0161eb3be364eabbbcf5c8e59a3a989ab03e77d5#tokentxns

just some debank wallets
https://debank.com/profile/0xc2b1faa0a2615c6e315596dc6cbe3c1049c0aa0f
https://debank.com/profile/0x53716f7ff7949e06afaeed5aa169ca31e53d7d46
https://debank.com/profile/0xdfe9e837a7bc21b0c928066e471e542ff75d3831
![proof](https://github.com/connext/community-sybil-reports/assets/108975905/fd1f5109-8853-4153-be80-e1be83471fa8)

# Rewards Address

My address:
0xe288b5284971a2225c1971db4a16a2c8a9902b40

**Comment by ArjunBhuptani** [comment] 2023-09-01 01:17
Duplicate of #12

**Closed by ArjunBhuptani** 2023-09-01 01:17 UTC
Labels: duplicate
