### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by hongtham4** [connext/community-sybil-reports#329] opened 2023-08-26 03:54 UTC
# Related Addresses

**Group1**

0x04c13419c75371bd2ac2e6abd483c0880b1521f6
0xad6c608a5383a9251b0441bfd605805cc21bd7ea
0xb96f27e36ed22a78d3f6b9c27e54318ebad5f5ad
0x1abb85e04a495a7b817face01a1fa072757ddb3e
0xc0f9ea984b4a523cd6e50a6923fe54e1dd68d287
0x21c2f8e26586781ba8a744795932373e2bf53beb
0xcbfc0a8a6e1b8ed0954dde5d7692191bef37c28d
0x39ef2a06ae6dd93a1978179bff7fc252ce1e9d91
0xe40cdea19d16bafe30438aa4b362be8c24e0a4e3
0xef3574fb33ef2447bf84175501ed45cbbc321bc6
0x5259bf7da0f3b02150ad01cb360ed31f8c787ba2
0x526ed06569b73f093c4d32348bf442023a9b8229
0xf77cffb2880e0c51cc112a87c1b0c7ff3a82966e
0xe89c074cb92a32514c144a0ed26e3deacb0437ba
0x5ef5b346ccdcce1b8fadfd7b9280a11d23ffbb1b
0x5f307aae5c1498f5d4634d4f19e965bfb47776d5
0x622e2808580d56f7f52c469d7c5b544d85aeda76

**Group2**

0x061b933a07ae5a5f017a80192dbf7de22089c417
0x0df8472b5010bcbea3cb51082f51d3a4070fa1a5
0xb6073601a0fa58ba56ed086f70e64de62e2799fe
0x1542820bfc39f060e2a5ff084a70ad365b4f8f44
0x176ecdf40679317b190ddc387e0a1d421c6cccf9
0xc56ea83f6cc9a6052c175dc2b90bc8add12e2649
0xc74e30942641178c49e4027b2a7fe42b26291ab6
0xc8e486156d8476b0339fcb9176aeeec224b4d96d
0x265e2cc3296d6dc744b600efbd35b306a077462e
0xd7c6b94cf3aefec71f96b24d5360aec0ff4facc9
0x388afe81ec5756711f22291351353d96bab58c50
0x45c05ab756e96c243fd4c6ed3b9f7f784bdbceba
0x45e9d90e7cae6da29845362bc3f388156ca611ba
0x46a2e9798aa25ebba6cfeba26ea8719e2ce90f83
0x84f98516aef92af85f3cd9bcb78c02e87a075779
0x8cdfe5c12ffa1f298bf625ca13362b5e68af1a46

**Group3**

0xb143c0b758d9b4a64ea395ef134e19c9f9cec5a7
0xc27bc0d8e87771409f9bc4580e1112af3161bb1a
0xc92ffdda5764b44cec572406bffa41fe70130385
0x32e65eb039bda251adc4989dc4cd778c7a1a17a9
0xd7f665892a1a49cd374b3abb2bae9aed5b83a227
0xde599900b82a732e49e75f696578fa6d1a8a97e5
0xee260f9e928fc2716d8c9b2ebf445dcbedda3232
0x4c6dbbabf3402e72ab8b500197304995b991383e
0x56a06a7c71e7bd67a191f129672a0d0b66e5d0e2
0x5c0af1a08ca859119b5f016e924605dfb1aee12e
0x5ca84e42414a066684d0477cbeaaa302f8b575c2
0x623b9233fb78c9ddbd5d788b3981fbf26c0f6063
0x6c7431257e2041f2f160c43471669f6eaba368fc
0x8d51b1997921d8d6db4b5e6df0ad57642dd39ae5

**Group4**

0xa636c5ba9c342978ce1d9fdc551e331a4d25344d
0xa8d8802fcdbfa82fe71657f28091344fca0dad75
0xa9a1848aeb76edddeac27a307f9e59e55c0dd4cc
0xae62730868e82c2e8a7757cc33671773a2814c23
0xb77d4bf7e8e4b67232ee54d387cf9736b97b7052
0xbe12758c6618abc44f0bf2ef69779220463f5cca
0xca2a4e091767d2fb2014e0db34f3d7415e0b6e56
0x2b87f369fbeadcedac14cf8f57a3b0aec0606b99
0x2bbad4d9668ab7e1cc55365ac471e0be21cb2909
0xfc78d986d5ca65c41ed20a2a7a937463e33994ea
0xff7c84e911de53f32d5a62b7048c5ca2779edd50
0x85afb4943f783657586fedd0854275138b66ce33

# Reasoning

**Group1**

ToAddress | nonce | balance | From | Fist-Hash
-- | -- | -- | -- | --
0x04c13419c75371bd2ac2e6abd483c0880b1521f6 | 26 | 0.809569703 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x23045050298945561fcdc43621180dba5ee54320943525c763924f3a50cefd12
0xad6c608a5383a9251b0441bfd605805cc21bd7ea | 28 | 0.707045424 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x11a202697e614c96af617e71fa719564505cd34afde935bec027213103c8440a
0xb96f27e36ed22a78d3f6b9c27e54318ebad5f5ad | 32 | 0.785460968 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x06405f955ef0eab7644cb9c9ade86f325a53ef6c7bb7885c2d200188ed975a5d
0x1abb85e04a495a7b817face01a1fa072757ddb3e | 26 | 0.885683333 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0xe148d7766e38d9df7d3f436cb6a153f3aaffdc0f13a04aab7c4ae25206f63f90
0xc0f9ea984b4a523cd6e50a6923fe54e1dd68d287 | 24 | 0.81742233 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x0acdcd477a648027b6ee9d3ab3d998d69fa087ccbaad950f427b3eecebb3f706
0x21c2f8e26586781ba8a744795932373e2bf53beb | 25 | 0.827428508 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0xeea202b779548689a556ea7ab504cf67578ba27d75d743f3c6fd95938b51f7c0
0xcbfc0a8a6e1b8ed0954dde5d7692191bef37c28d | 26 | 0.767232347 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x2d8ffa4885fe9dcabc5ef13fdb118cd83d4185178f09213e2ce474613448b05d
0x39ef2a06ae6dd93a1978179bff7fc252ce1e9d91 | 23 | 0.822406166 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x9caaac0e9a2d2390955aa9af369db4356e4c99010948a253ca48fcf63947624b
0xe40cdea19d16bafe30438aa4b362be8c24e0a4e3 | 25 | 0.852748507 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x8802b722058e9f9a6b5af3af73e70fc3b3ce3ed59ebbe9b3494a55b9d31fd6ab
0xef3574fb33ef2447bf84175501ed45cbbc321bc6 | 26 | 0.793264976 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x2ba957dd424078174fb0549d56fe1fefa3aa129733cf4adf3b08deccdf4ee5a1
0x5259bf7da0f3b02150ad01cb360ed31f8c787ba2 | 26 | 0.815607707 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x503eef1d076a960158fad2387a15515f5ea60b95a5e63715bff473f0219bf756
0x526ed06569b73f093c4d32348bf442023a9b8229 | 24 | 0.897892746 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x22fe4b5d33626a842eb2148f7cae33d6774d03c750a252dbbef35b5f81f8edd5
0xf77cffb2880e0c51cc112a87c1b0c7ff3a82966e | 434 | 0.649290619 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x71f5a6d29639af9b9c5ec73b6a156c062575aedb52055c3f54844d72f9028cb0
0xe89c074cb92a32514c144a0ed26e3deacb0437ba | 24 | 0.843219075 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0xbb19c7d095c53b2adbb43b28919e31cc3eb51bc782cd8410cef2be4d2d90d06a
0x5ef5b346ccdcce1b8fadfd7b9280a11d23ffbb1b | 26 | 0.761530451 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x4fbe3f030765a2fdc836cf36eb8632d34194aee73daea76914bceaef6c53d795
0x5f307aae5c1498f5d4634d4f19e965bfb47776d5 | 25 | 0.792176111 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0x32ea663babe6412336d15c69e5f7726a83b62386f202a89537b5b121de157297
0x622e2808580d56f7f52c469d7c5b544d85aeda76 | 61 | 0.622354394 | 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 | 0xb0d7b2f004e054fce317e3a4de0328a7e04ebbea4d4659bf1724b517f4a50553

First matic received from 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 
Time: Jul-27-2021
Value : 0.05 Matic OR 0.1 Matic

Most addresses have a lower balance ( 0.6-0.9 MATIC ) and similar nonce characteristics.(24-26)

Most addresses Total assets on the chain are very small, less than 20 dollars

The behavioral patterns on the chain are almost identical , Polygon chain protocol : 0x / Zapper  / Synfutures 

**Group2**

ToAddress | nonce | balance | From | Fist-Hash
-- | -- | -- | -- | --
0x061b933a07ae5a5f017a80192dbf7de22089c417 | 21 | 0.344113713 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0x35d3b7b769ccd367430d4a840dd1f368355bf9a086e91d849e708db986995637
0x0df8472b5010bcbea3cb51082f51d3a4070fa1a5 | 45 | 1.350389725 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0x0444f4632e77e8d5a768525e993011842b5d022b18bcab769a1b6cd5e6f902ac
0xb6073601a0fa58ba56ed086f70e64de62e2799fe | 48 | 2.999940917 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0x40997c4fffe6b1b9f2bf5d51ab63dca8de3d19efe88e51f2c542f0680ef2f11a
0x1542820bfc39f060e2a5ff084a70ad365b4f8f44 | 47 | 1.131364143 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0xe9d6b3a8760377cb9c33f8d3811ddd961a2f5a0296c44d6d7b90d12c9e9591ba
0x176ecdf40679317b190ddc387e0a1d421c6cccf9 | 45 | 1.190709578 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0xb779cbeb1fc556f91f16a9de2f05a843e94661aaa2317383ba805c9e3b7065b9
0xc56ea83f6cc9a6052c175dc2b90bc8add12e2649 | 23 | 0.478672549 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0xa6cc47248b4712024e45993172ddf9273a8f870f9059c72ae7c8bb9621fe361d
0xc74e30942641178c49e4027b2a7fe42b26291ab6 | 22 | 1.469781132 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0x895e404daea67366d79c54d7459284623aa3fcdcba25f0110dcfe1bf8db9b9a3
0xc8e486156d8476b0339fcb9176aeeec224b4d96d | 30 | 1.47035204 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0x09566054a7d9dd3eaabc768a32aa5b8b38dee65a383085dc4c18d71d64955448
0x265e2cc3296d6dc744b600efbd35b306a077462e | 25 | 0.304848782 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0xa0ca1410ee20fcbe649ca0b4f9739c01b80252d2b24e72a105773f888248b0b5
0xd7c6b94cf3aefec71f96b24d5360aec0ff4facc9 | 32 | 0.510797458 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0x2d8ddd924050758a071ff88aa5470219006a1845d1a14d1994635c7c9042c0ae
0x388afe81ec5756711f22291351353d96bab58c50 | 32 | 1.325686678 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0x8bca674c33580a61acee5c8c1320faf2ea4d07d95f08e804bc87d2fedc086d57
0x45c05ab756e96c243fd4c6ed3b9f7f784bdbceba | 43 | 1.396313025 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0x777f762974cd001fef0ac6676b2b7aca64126d42a828e82474978e1c65477d67
0x45e9d90e7cae6da29845362bc3f388156ca611ba | 34 | 1.31301709 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0xdf684359dc135d5a91db7c75698f8b4c32a960b34891a9d28baf55dbd659bcf0
0x46a2e9798aa25ebba6cfeba26ea8719e2ce90f83 | 45 | 1.813446745 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0x83eca9d644e92c5d81e80b05c51f7589ecbf7b9d20c9320818495401e08936f9
0x84f98516aef92af85f3cd9bcb78c02e87a075779 | 46 | 0.824643073 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0x40632ccdd50b6945659b413b6640daeb5180ee1678c535244bd682d4f9037323
0x8cdfe5c12ffa1f298bf625ca13362b5e68af1a46 | 21 | 1.334310816 | 0x49d83abeca8537b41bb5b65a97df147774634444 | 0xd99232cbfe6714add330f4af0e0991a6eb1fc6d4f948eb0aff300b97baf52431

First matic received from 0x73cc14479f5744bfb593625aff9fd17398cfd6f1 
Time: Nov-13-2021
Value : 0.3 Matic

Most addresses have a lower balance ( 0.3-1.5 MATIC ) 

Most addresses total assets on the chain are very small, less than $2.

The behavioral patterns on the chain are almost identical , only trade on polygon and gnosis chain

 protocol : Gelato / Synfutures

According to Debank, these addresses were created at the same time, about 650 days ago, on the day the matic was distributed ( Nov-13-2021)

This group of addresses and Group2 at [Sybil Report #326](https://github.com/connext/community-sybil-reports/issues/326)  may be controlled by the same person.

**Group3**

ToAddress | nonce | balance | From | Fist-Hash
-- | -- | -- | -- | --
0xb143c0b758d9b4a64ea395ef134e19c9f9cec5a7 | 149 | 21.67015017 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x9e1cdd89dd194b6ea04762c5ebaa7f580386da6f31be49217395bd923ad1251b
0xc27bc0d8e87771409f9bc4580e1112af3161bb1a | 176 | 28.80073795 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x758f990f9fe247e65c23daefc9e2dc276615896e425e49e77981520e20df5e58
0xc92ffdda5764b44cec572406bffa41fe70130385 | 94 | 2.583744165 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x06250b88d84168657b169b2d282b728cc3051affba10b68d18a9c8044878e3a3
0x32e65eb039bda251adc4989dc4cd778c7a1a17a9 | 97 | 3.237074755 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x811c87a9a4c066375316beae3a4d5f438930f1b684dda25aea1621c3a73d765b
0xd7f665892a1a49cd374b3abb2bae9aed5b83a227 | 110 | 4.741277212 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x0d01b1647b1884a6618ef70a2f4e68caedc33486b442cea7e5e9b3fae7d01471
0xde599900b82a732e49e75f696578fa6d1a8a97e5 | 120 | 3.254256684 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x669e38ebf657a5ce39eeaeb7fbfbcf4418b305a1d0c026ec29ef7b4f6b4f3ed0
0xee260f9e928fc2716d8c9b2ebf445dcbedda3232 | 153 | 3.987715858 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x3327d2f7349189af1f54dd2b9a2999d3ea73919d524a64687aa01cd19e543c12
0x4c6dbbabf3402e72ab8b500197304995b991383e | 249 | 7.99802081 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x2aa5194aa3decc22432a89498e063bb3b7e952e12f5fa4518a2b84457e9d1764
0x56a06a7c71e7bd67a191f129672a0d0b66e5d0e2 | 96 | 5.159739316 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x12389275c515409006c5d26df1a4c2f6edcfcda346a58be4a3986744980716e5
0x5c0af1a08ca859119b5f016e924605dfb1aee12e | 144 | 6.785350569 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x0f18fff890de7a839eb399dcca3385f9bb24f5960d06753398f1c770a80ac87f
0x5ca84e42414a066684d0477cbeaaa302f8b575c2 | 106 | 7.685002412 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x9555683da7c02e4360d159d74dbc1673c2dd3d1ce85991b4662d89bff747a51d
0x623b9233fb78c9ddbd5d788b3981fbf26c0f6063 | 138 | 9.680293045 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x3aad3108f7d49cc8c46bac38574781769e1a4a230429b50c509378a2bfdabd65
0x6c7431257e2041f2f160c43471669f6eaba368fc | 156 | 6.677068701 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0xc37e31bbd6404287d3aef9cc3aae167919390b47f02460e3f98e3d5c7099cb2c
0x8d51b1997921d8d6db4b5e6df0ad57642dd39ae5 | 145 | 9.688463819 | 0x43d24481877e99b4cab78102eb37441c60701674 | 0x6899668e8800cedc87ab5975c36f9eaadd6ee6834355ec8024454505cd439395

First matic received from 0x43d24481877e99b4cab78102eb37441c60701674 
Time: Dec-14-2021 / Sep-14-2021
Value : 10 Matic / 2 Matic

According to Debank, these addresses were created at the same time, about 911 days ago

Although the times are different, the addresses are often meaningless and continuous across the chain, involving the same Dapps: chainhop / hop / li.fi / gelato / cbridge

**Group4**

ToAddress | nonce | balance | From | Fist-Hash
-- | -- | -- | -- | --
0xa636c5ba9c342978ce1d9fdc551e331a4d25344d | 982 | 12.62821103 | 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 | 0x99d88d78f4283af2005b48b6f952e5332af41866276b429efe5d2e26d3a56d2d
0xa8d8802fcdbfa82fe71657f28091344fca0dad75 | 957 | 13.97369534 | 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 | 0xf13729e0f6ae81c5557cb9eae27fde99cb25b0ebad188352e6d3ef3097c991f8
0xa9a1848aeb76edddeac27a307f9e59e55c0dd4cc | 1034 | 13.9470889 | 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 | 0x28171fbf4c917f19954872661cfca25430818ad7eeb170eb6bc080ba5ab9db87
0xae62730868e82c2e8a7757cc33671773a2814c23 | 999 | 13.2872917 | 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 | 0xef89a8570a6d43778fd04a6998d01393ee8405bcd3ae3ed09af2fbf45c30322b
0xb77d4bf7e8e4b67232ee54d387cf9736b97b7052 | 977 | 12.77911754 | 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 | 0xf8bc2dac20a41fc7efddea155027fda1c373c312a72584b079e886ece896d7ad
0xbe12758c6618abc44f0bf2ef69779220463f5cca | 968 | 9.273064764 | 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 | 0xe2043949bad5b91a10c4508bcd5a33e6202d8d32b38a1c35f912521f7df574d8
0xca2a4e091767d2fb2014e0db34f3d7415e0b6e56 | 981 | 12.68481097 | 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 | 0xc95de766b9273d3971e1e7446740654b8b73742dbf7c924a7385943378cdf728
0x2b87f369fbeadcedac14cf8f57a3b0aec0606b99 | 981 | 12.69915279 | 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 | 0x55aff5cc3b76c902755b6416af423fa1aa6ca18e3fbeeb97bd3e5362d3870abd
0x2bbad4d9668ab7e1cc55365ac471e0be21cb2909 | 970 | 10.80827877 | 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 | 0x98e3c4a91aa541f5a5c9ea790ec8c92eaf176e5a392207be1d75ea9b6e55d2d5
0xfc78d986d5ca65c41ed20a2a7a937463e33994ea | 981 | 9.558721075 | 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 | 0xc2049f5075853f2e3cc7d4b33627716ef104a80b1e95297f4dedffa5c74309dd
0xff7c84e911de53f32d5a62b7048c5ca2779edd50 | 1013 | 9.376017202 | 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 | 0x8efc31520504e2d717bc3775e45d2d8d5ec31ac417cada8d238aa32b5589ab89
0x85afb4943f783657586fedd0854275138b66ce33 | 995 | 12.3225324 | 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 | 0xe5aa5f6203ef1cb9f832d09e74d467e7198f95e7be24be5ef7320db1cc1231c7

First matic received from 0xac34457d13cd6bd41be54ef3644e5be9ffe683e4 

According to Debank, these addresses were created on the same day, 1041 days ago.

 similar nonce characteristics.(950-1013)

Chained behavior patterns are similar, with one recent chained behavior: claimMaterialObject - Phi

![image](https://github.com/connext/community-sybil-reports/assets/143180414/cf6b0268-7ef7-44fa-afb2-c9cbdf474a9e)
![image](https://github.com/connext/community-sybil-reports/assets/143180414/03135d5b-4b77-4826-8128-a9aea97835db)
![image](https://github.com/connext/community-sybil-reports/assets/143180414/a637e519-2035-4896-a322-ccc73d8042f1)
![image](https://github.com/connext/community-sybil-reports/assets/143180414/6765ede6-caba-4eef-ba68-6adb19488f28)

# Methodology

via  'https://api.polygonscan.com/api?module=account&action=txlist&address=%s&startblock=0&endblock=99999999&page=1&sort=desc& apikey=YourAPI'

```
const ethers = require('ethers');
const provider = new ethers.JsonRpcProvider('');
  
let gas_balance = await provider.getBalance(address);
let transaction_count = await provider.getTransactionCount(address)
gas_balance = ethers.formatEther(gas_balance);
```

I used the code to find the hash of the first payment received by all addresses on the Polygon chain, counted 10 groups of addresses with the same starting address, used Ethers.js to find the nonce and matic balances of the addresses, and found the correlation between the addresses in the browser and the addresses on DeBank, eliminating the ones that didn't have a correlation.

# Rewards Address

0xFCDDF1BD37cabF95442fa587e3387100Bae108Bb

**Comment by hongtham4** [comment] 2023-08-26 15:00
# Additions to Group 3
## Related Addresses 

0x7dd4945cd37bf002f81d4e2adcf6157f88cee150
0x56a06a7c71e7bd67a191f129672a0d0b66e5d0e2
0xd7f665892a1a49cd374b3abb2bae9aed5b83a227
0x32e65eb039bda251adc4989dc4cd778c7a1a17a9
0x5ca84e42414a066684d0477cbeaaa302f8b575c2
0xb143c0b758d9b4a64ea395ef134e19c9f9cec5a7
0xde599900b82a732e49e75f696578fa6d1a8a97e5
0x623b9233fb78c9ddbd5d788b3981fbf26c0f6063
0x8d51b1997921d8d6db4b5e6df0ad57642dd39ae5
0x8ed9a9c9b8e33314c9e64428883cb574b0442243
0xee260f9e928fc2716d8c9b2ebf445dcbedda3232
0xc27bc0d8e87771409f9bc4580e1112af3161bb1a
0x9dc4367227a288a59a099e884fd80dcf48d2cf64
0x4c6dbbabf3402e72ab8b500197304995b991383e
0xc92ffdda5764b44cec572406bffa41fe70130385
0x78fb513243ef659d05bc49c43af530fbe8d32477
0x5c0af1a08ca859119b5f016e924605dfb1aee12e
0x6c7431257e2041f2f160c43471669f6eaba368fc


## Reasoning

First AVAX received from 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 on AVAX chain

to | nonce | avaxBalance | from | hash
-- | -- | -- | -- | --
0x7dd4945cd37bf002f81d4e2adcf6157f88cee150 | 9 | 0.074654972 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0x0388b3511137985ecc43618760bf994ac6b625c50611b0420db0a9c45ea4b155
0x56a06a7c71e7bd67a191f129672a0d0b66e5d0e2 | 17 | 0.007104015 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0x325e2ea38762257c8368cd463f545cdc4c9b94203af564618f5b71ac92115ebf
0xd7f665892a1a49cd374b3abb2bae9aed5b83a227 | 12 | 0.230776418 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0x8cfb9bce6b66b383af793a82a7b889bef766595e06865eaeb5afb2ad5ffe49bb
0x32e65eb039bda251adc4989dc4cd778c7a1a17a9 | 10 | 0.040183755 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0xde177fddf4ade53d3e24b16bae5e79fa1c22953112a6ecb935b5897df4dc1c55
0x5ca84e42414a066684d0477cbeaaa302f8b575c2 | 15 | 0.017266167 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0x0600e38b7db55981408e0de53ea06f08355cd1fea91f6165ca6038a1f1940d2b
0xb143c0b758d9b4a64ea395ef134e19c9f9cec5a7 | 33 | 0.861111028 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0x66a5448b1e149798cabb9b28d64db33354b5927441c1def9244b3a483dbdf59d
0xde599900b82a732e49e75f696578fa6d1a8a97e5 | 20 | 0.208524841 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0x66b873ce37913fecad26087e530b5a807cfc83c782a880c2672f61d79c925847
0x623b9233fb78c9ddbd5d788b3981fbf26c0f6063 | 18 | 0.055271348 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0x9eb9eeada3cdeb0557d74b0de1aeb8b7dff0e570668dd9abb633c384e4199e19
0x8d51b1997921d8d6db4b5e6df0ad57642dd39ae5 | 53 | 0.073047729 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0xc72d5f13f8750c1ed96b3edeb822decaf44aed7766791ab9fc23b8dab0e4b338
0x8ed9a9c9b8e33314c9e64428883cb574b0442243 | 18 | 0.013612939 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0x688bbefcc3dab88d823362f247e2ca3745566df2f5bd745c120d637d1d5fb55f
0xee260f9e928fc2716d8c9b2ebf445dcbedda3232 | 19 | 0.054004228 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0x96104e940237d9b53c05e3a7773e33c20debdcaa43410d76d24710a67b842664
0xc27bc0d8e87771409f9bc4580e1112af3161bb1a | 23 | 0.057189375 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0xc76bab4fbe9f35e8f61bebf7c18172f04b4f0c4d3cc70e53e108c8f04fc6e62e
0x9dc4367227a288a59a099e884fd80dcf48d2cf64 | 10 | 0.03879242 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0xc39a5759a30c50288ac750872d1751a3c8d385f225642588e2b8c9e75545d2f3
0x4c6dbbabf3402e72ab8b500197304995b991383e | 73 | 0.238997757 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0x2014e2d85876d4f584afb52f6fd67ef3c731fd0672b997b8d532b877d5791c6c
0xc92ffdda5764b44cec572406bffa41fe70130385 | 12 | 0.216198438 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0xb8625b4dcc5e7a9f864a81b43de5f6e2a376b27fd5ec59e5ced27f72ab114d03
0x78fb513243ef659d05bc49c43af530fbe8d32477 | 17 | 0.430724714 | 0x46dfd5231a7f74cc827abeb36be3b76df464dcb7 | 0xfce24a04ca3929cf6ed64fb905e6e2572c3cf08c0345915a6093c2bc7d340b70

**Comment by A-Keyboard** [comment] 2023-09-02 00:25
Group 1 is a duplicate of https://github.com/connext/community-sybil-reports/issues/217

**Comment by just-a-node** [comment] 2023-09-03 01:39
Valid clusters

**Closed** 2023-09-03 03:51 UTC
Labels: pending application, ts
