### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by devstude** [connext/community-sybil-reports#297] opened 2023-08-25 20:49 UTC
# Related Addresses
0x4e5154bd3fa9caf522843e7d4d4537d059a1e2f2
0x9b1151603ec672a804f0b8b8d9595be0fb283097
0x9d5cd484adece04cb56491125cfcd5cbd7a371d1
0x3c31b773a522b265237db2f39b8fa9e08f967285
0xc2ba854f7e6e3ddbc6700a86b1f04bd8384e9d5e
0xcaffc8c24bce179386fc22099f5f496d0ec27f78
0x13dccea9bc2f2c3bbd57053250ea78b5391af6d8
0x657681876ca4b029c90e60280ecf06120b2ecdb9
0xbfb24e4ee9ad5138c4c672e040776c313787df22
0x17ff9c7091e725fbdb30eb8a078dee541457df05
0x3986fb2eac009e617b467651485f216b02445654
0x0e91627ce37fbe70580d3226c2dd19014e95a95a
0x0777b8308711bd5742df9169d9657f93591aaedc
0x6514826227c000745880bca67fa8d16c2f4eff20
0xab61884519f4845ba69ae6b54f3f4030f201448c
0xf27b75403f6f2df02ecdef71b2652dcae2bad712
0x2bc9258cf6a3dac17d1106ac92d160938ee08810
0x6cd63cd29ac1a4abce0266b451f8b960463f9a68
0x82381b780023e23116fff0de674806d29461c875
0x94a3f772f84758cde176fb8eeda08e776c51efb2
0xd44c814e1a43d7a6256b311e585cef5385b8c2e5
0x36d0c2a355f00bfb4fec42a959f9cab3d04507e6
0x810955e73ec01f5ca9d3e1bc8cff606fe861344d
0x01f89319e731d7bc35adf1afc4c1e02c98200f5e
0xac356ef9a2945c5487a79e7b853f0bda9d076b9c
0x734959515629dad5556dee658dcb729c36468572
0xdc0aa19f0afe6a914bdd039abdf7a42373f66a10
0x957de60c944cbb070d582d5fa619114d338569e0
0xdd2851765bcbaa12d77b421e1f999371447693a1
0x7d2fff0310f1f22030585d12556add9287b58c31
0x470484829cd7eee5465d51b15eb47db653024486
0x930cbf954e89d8a1f709a4480bcdffb19e1354f9
0x12e995f3202bc82f24a54dfa3ba8589cce741a93
0x770a2ce69e65f7e57fe8b166842a6ba9b1517408
0x697e92fc7b7c701bc73d0f75bdc97a58e3022b8f
0x945ce58e7e27c329a782b89a138f92e1c2995a63
0x2e8c6bdd3a67eca81446588ce4f9814a5c44b944
0x605eae76ad5721ba5e2e52300bd6566b29eeb385
0x3e281072332713da7ce20f56f2e6f7b5b987ed6f
0xc67d3ef638e9c107423d6569cb831c547e16117b
0x081bb1be8a8e22bc8a7d85cc456646ba5486d46d
0xab43d2597ae3f4aacf1bccce02ead58c3fff808a
0x73b5edd218956e4abb8aa150ebef30ecb3ceea74
0x86bd7eccbc0c2cfab00469ba34c86be1044871c0
0x2377d08c247d3f97e76b158e625a8c497ac35eba
0x617a085edf91d563823baa2806afe75ced60086e
0x058af57ee792b55b07161596b924d0b0db8437cf
0xb3977095fa9aa8372fe5441800139e8563efa054
0x932bce2bbaa7b81ce28dd0f0976071114a6c222c
0x901f3f32ed14d54c2482f784206f09a8b75e15ea
0x632ef6723c50f66ccc3b221c61e6ab538619ad2b
0x02627387730e2d5f09f828478527fb28b83acd58
0x288cdb15420a46da1a4e762943b91376cba0b4bc
0x6b50168f8523ee28f88aa3baf18dbd034160b916
0x0328472a6e5d49b0a0c4f77acf2ecb1990408a88
0xd0ffe3ff0e847d7c1e4cf7217b1725762a331581
0x2cea7e3068c1973eff01d22cb51cf64bd8a9af29
0x06995faf8f6eb3350c11487a2fdaa5a38efffda4
0xad680aad3e43fb178403aa9dc454c6b7db169b4c
0x8b418b96c49873b2feb866c68a6b30aebcfdea6e
0x174d8ddb8af41225649859f51ee7ee1acedda0a7
0xab28f832c51ab2cfeadb840800698ad9607b37d5
0x9609d5ef3add3f2f1f6897dd8b4974efdb27c5f7
0xd81251fd1ed906d2e023cca2827d83df3ab219b9
0xf0b64335e9110c43848f610760945227ba865456
0xe85d6e3fb5c8c14acd9f574f8c0cd9c17e559cb4
0x4ef6019663736506de382693e20444ad68a75bf4
0x5d3ba5bf540c8ff5c41c8af5f83e6c0d66b5082a
0xeb11850fb42f73d3fb96309419a4410dbf1389cd
0xd47307c0f5ca0cab03142f2720d28fd60b8e2cd4
0x8da934710b73443b12d9469d668748bfccc4e93f
0xd57b0610e9026493dbf8506e906bbd2a2e7859a1
0x39a7fa487c5c1f35da457f5c118740a2d609f925
0xfdf1c06b20ce5e724234882818f636774b5e3dd9
0x1a474d4ff9aa08170c155f6a9be773c8379507f8
0x9ea0717541b0a239c0d5a30c3ac820160297f977
0xf1edb84c50f813fb01afa8148b74b749960279a0
0x4551e6ad0ed1727c36f148c30d8dd3a287def1bb
0x57b8ac115b02619ed8e2b3d2d5d3ad3396734537
0x4b04f38792e6075e09c81db20731f272b73b4e1f
0x07c7119bc14d18a09fec9756d0efc4fb468e72ab
0xbb864ddd38b6d4bad9a7df7cd207d10e9d2c98e7
0x90944a242b109a98b56fba1e6dcc931075c9d6d9
0x3bb66bf98470914587e00c5e5507bddf6ec44310
0x50bfc3e20fca43450b0e1a45469c9048d46c886e
0xe1ec2c97dfea4e21a5eb0cc4ef61d20cab988c57
0xbd2845ef2fb1e073abeb5548940b3eeddac94f2b
0xd024ac440241050bcf45c2c842b55d03e3d1a14a
0x75997bbbafe2c1cff7f4251c741be1816fcab55b
0xda6080383cfe15a19b0112ba5863240b0083dfe2

# Reasoning

All addresses where initially funded on Ethereum mainnet from same main account 0x4e5154bd3fa9caf522843e7d4d4537d059a1e2f2 (which is also eligible for the Connext airdrop) with same amount of 0.018 eth in 2 batches:
1st was made at 2022-03-09 (39 wallets funded one after another with short dinner break)
2nd batch of 50 more new wallets was made 2 days later at 2022-03-11 (with just a few seconds delay between fundings and one 2 hours break)

# Methodology

Those accounts where found by running dune scripts that analyze initial wallet fundings (for wallets eligible for the Connext user airdrop) and manual checking of same time/value/initial funder wallets. 

# Rewards Address

0xEd3aAD546d663084794CcCcA6987089395FC1760

**Comment by ArjunBhuptani** [comment] 2023-09-01 18:57
Duplicate of #63 which was posted slightly earlier

**Closed by ArjunBhuptani** 2023-09-01 18:57 UTC
