### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by sybde** [connext/community-sybil-reports#49] opened 2023-08-25 01:05 UTC
# Related Addresses
0xa6bc0d73042cb6b99b71de22838c9225729ea32d
0x7aB89e577bCe4C35EcD7546F758F1C41F9777cCf
0xF7E10ae6B052bC1452139043B00D49a80Fa9A3d5
0x4E9a4bD232B23D95D75Bd553dA3025400825309e
0x390fd846c06Ff8e98E60B5FCde42c58AB33A9FA3
0xE4C79ACfD622B312eeFc37804892Ef6847c41869
0x34d56CaE0b0855D63EAEcd573Ae9DCE76E603f89
0x6e03F76fb77C3b27A1742BbaB1fFA6aB4907eD5B
0xC2feaD641B04491b0c7dc0c405289F4373a7cCa3
0xEA1c10435Ba64c02aD3d7B1C15F7255222967BC1
0x762009518245AfcB8CF624A4116265eA7745F6AC
0x938e3b0e9e70607c50C2629fA434B9a4e5f28421
0x486a40bA29A5fA223ebF8A6c5cd4287517264FCd
0x495446F7fD604608A23009fA12E65d0a7554b5F3
0x7c042956468e5993a994008b5966EDb3fD1b26FD
0xA9A367E474501818ebAFf858473d8639D19F9F3b
0x9308Bd4fDEc064521ba86D61fbe606569964AbB9
0x4aF997F78067dC2458CDe261FFAb863afa5Cc357
0xB35a83BDA02c2cb5af44A8AFC79431F9C11E505C
0xc759F81e08614ceD125A74aE672D1AF7a0429993
0xE2B6b8E9aa2c9C9e16A672DdC655B4712F28Ce86
0x0f87452A7Eac3BCFE90Fe4187d2f922d1D6699AE
0x9152B598995EcD590DEe9C67f649E1E8533af46f
0x2e44BF02BAA8a4D83A08FAdB3Fd9e901A0c53108
0x8CC2c2B764d5A0E76e45AF8bD037bd989A16B2c9
0xC0321d0A3624ad42313103190aEFEBE00B9C74e4
0x4653ff13b065B170f28C03871E343Bb2425ADF2c
0x5C01D5dC0cD8681727763a1c6Fa5B07E94D01079
0xbc3A065464a2839aE268861356328ce910783ad3
0xc7656Ea29f8382Aa176e122aEed36813D1fa13e6
0x0d3Da428dD261410aaB95ef751ebB0B0F6F04c0D

# Reasoning
received funds from one address 0x192553385d46bc946a35c0870c876cee52881c08 at the same time to all wallets in the amount of 0.1eth arb and 750 usdc matic between (Feb-21-2023 12:59:01 PM +UTC) and (Feb-21-2023 01:14:02 PM +UTC). Further adding liquidity connext 500 usdc on all wallets at the same time (Feb-21-2023 12:59:01 PM +UTC) and (Feb-21-2023 01:14:02 PM +UTC) All wallets have the same activity in the same time

# Methodology
I used the service https://platform.arkhamintelligence.com/
He pointed out to me the connection of these wallets with one other from which funding was carried out, also by visual inspection of the transactions of these wallets, a coincidence in time was revealed in the conduct of all operations.
https://platform.arkhamintelligence.com/visualizer/entity/0x192553385d46BC946A35c0870c876CEe52881C08?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1

![Screenshot (15)](https://github.com/connext/community-sybil-reports/assets/143136925/433304e8-a1b6-497d-b8ff-297ea6d4e630)

# Rewards Address
0xd52bb9d212eE0941Fe375D569D67e7Ab7d8d1C9F

**Comment by ronaskin** [comment] 2023-08-29 10:23
![Screenshot_10](https://github.com/connext/community-sybil-reports/assets/137379395/07a75b99-4840-4ac3-9362-f4808f8f03d7)

**Comment by ArjunBhuptani** [comment] 2023-09-01 15:06
Duplicate of #46 (really close though)

**Closed by ArjunBhuptani** 2023-09-01 15:06 UTC
Labels: valid for team review
