### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by unrealxCode** [connext/community-sybil-reports#210] opened 2023-08-25 14:34 UTC
# 1
# Related Addresses

0xcBb9a9ac75aB376C28228B34DfAeb293fEE9b8AA
0xE0Fa8Ffa1ADA0AF37164a355394c251B854e5a50
0x6BEf233356DE2c4e7c2e955FD276BF174D9DE4e0
0x5e754198bA446d649961987dEe6Eb0bcF13D1168
0x1F6e94691561a82E45eAb8D3020bdAc91e142f91
0x3Ee135E0EB00F355fa05eAFABFf72C493121D728
0xa91C48BDd24641f6773A19028bfA8Cd676d37872
0xff51FA4ae7E05A149139842d1058C641cc2cdF0A
0xFa859A032ec2dFcA5dEa507CcD384eFd926134ee
0x4c2bE77741570b1074fEB47E36eca1A8f09Aa9fF
0x907a37f4FdCaD959Ca182538CFD9A6745cD673A6
0xbB3C6C4925b285e0Aa237531B31E6D951a75A9c7
0xA9633c287288b5d4098B08506AaD92966b263DBA
0xC72050c99cE1538Db4B96F1C04ac6cAcF04Ae95E

# Reasoning

**All the 14 Sybil Addresses received exact 0.001 BNB each on BSC directly and indirectly from the Parent Address (0x6F5946B009B59B023b4aeF38058B2EB77959d535)**

Address 1-8 received 0.001 BNB on BSC each between 04:29am +UTC and 08:00am +UTC on March 29, 2023.

Address 9-14 received 0.001 BNB on BSC each between 08:20am +UTC and 08:44am +UTC on April 4, 2023.

All 14 addresses used the exact same Contracts with very little time between them

----------------------------------------------------------------------------------

All the BSCscan tx's from Parent Address to Child Addresses and to Sybil addresses are provided.

**Address 1 to 7 directly received funding of 0.001 BNB each on BSC from Parent address (0x6F5946B009B59B023b4aeF38058B2EB77959d535)**

![image](https://github.com/connext/community-sybil-reports/assets/100838740/f854e680-48aa-43a3-8e5d-945949a93dee)

1. https://bscscan.com/tx/0xe626747cb1631908f1fc0351b5af7010282f1f8c0e506e363d56fecef05710ca
2. https://bscscan.com/tx/0x079e4d5ae7894277b1070f3aa08d80ad0a10c8a2da6f96c160b258b45d6bb974
3. https://bscscan.com/tx/0x9877c7e5095aabe5231c46b11ae98835a8a506477a0a1a9355bcf7f05c7ba117
4. https://bscscan.com/tx/0x55e29a2abb7f4985e39c4d79b28b1cb3281035de548a7d6c1fb099e4354225a1
5. https://bscscan.com/tx/0x60e5d3f331e90cf830b018a93d512b21611df455d5a73f8cb486e3282ec28add
6. https://bscscan.com/tx/0x8d1d438e29886b3c0b293130bcc9e64670dfc7be3c8f29897bea6b52359f5100
7. https://bscscan.com/tx/0x9fd772b9bb6c4bd6e6db15adb2e3c0de20fd1c1e80f3b49f6849fe9bf81dc7c5
----------------------------------------------------------------------------------

Parent Address funded Child Address 1 (0x2ba6a5220658D04C368716805B0a88733B8C2EfC)
https://bscscan.com/tx/0xd9e0a1e0a44223261e9c36c89b56798930fab8dc1d5c7eaeda2658cac41ec916

**which funded Address 8, 0.001 BNB on BSC**

![image](https://github.com/connext/community-sybil-reports/assets/100838740/d2f2b7d4-6b58-43f1-a1db-8eee516595c2)

https://bscscan.com/tx/0x6b726fcc2084b8a30e597a5f7eb4c0e37ab7ed998f6d7d3e6c3bec1037637ad8

----------------------------------------------------------------------------------

Child Address 1 funded Child Address 2 (0x27F6D90fB3DA8df824ed7a9c98601a4824729fFF)
https://bscscan.com/tx/0x10c44508f9ea3e042e38d837975b9e281c8ed50779821e943a06463fadcb666a

Child Address 2 funded Child address 3 (0xBDa9d4360c496d916dd1d589a3A72ebF244385cc)
https://bscscan.com/tx/0xbea5f93c94c84121e820a47a118d853990eee8dee7ddef5111d1c3953e4dab01

**which funded Address 9, 0.001 BNB on BSC**

![image](https://github.com/connext/community-sybil-reports/assets/100838740/19d51196-1f2f-4b67-8e28-96d664bb28fd)

https://bscscan.com/tx/0xcc2fdaa6678a2e0d610b0c0612e5e28413abae92b2a4be6539f86925f8aed94a

----------------------------------------------------------------------------------

Child Address 3 funded Child Address 4 (0x6eFC15dc1653Eb8cE2934D12c64A86d829A62fEc)
https://bscscan.com/tx/0xef1c56dc3efd783e495db60d8ebc8aa3c40ab35817504734e0fd40d601ce9259

**which funded Addresses 10 to 14, 0.001 BNB each on BSC**

![image](https://github.com/connext/community-sybil-reports/assets/100838740/1436f487-d592-4542-8542-05e7f3df51b2)

https://bscscan.com/tx/0xe3595e90d82ed3676669407cdcfe590729c3bd0a4ba48a2d19f344929b3bee07
https://bscscan.com/tx/0x0c3eda2dceaf873ab7a7bfc78a655ae39c7ec0a53703253afd6186cf26effb5a
https://bscscan.com/tx/0xf209b19943b9167ae9d53bf3e5b8229389ede35f28d058374d02944ba0c6773e
https://bscscan.com/tx/0x6af6ac03e04e69a5c838d73be51eeb9a44bbe6f24ae107450715f444c01d5ddf
https://bscscan.com/tx/0x9255cb692fbc2f080b51d276d3eb2ab4486e541cb46342987c41c8e4e1c73e36

----------------------------------------------------------------------------------

# Methodology

How the addresses were funded was the idea behind identifying the Sybil addresses and what contracts they interacted with.

All the 14 addresses were funded from same Parent address, 7 of them directly funded from same Parent address, rest of them via Child Addresses which were funded from the Parent address.

0.001 BNB each was funded to all these 14 addresses on BSC.

All the 14 addresses claimed and sold the token SPACE ID as their first interaction with a contract after getting funded.

100% sure with on-chain proofs that these 14 addresses are controlled by same enitity/person.

# Rewards Address

0xbBb816d9b0886e4b4F6e38996deB635D5bA77A8c

# 2
# Related Addresses

0x3211f9eAb94b9656EEB91015875187Fb44Fc1009
0xDdD90053B6aAf9f2Df5C518158D09771Fa995C17
0x6B53f1A084572BdD09A433F06AfFFf0e35d81Ccc
0x98FC6112749f7663CC537Ca3330af68109891c09
0x3c9b541D0317276A05b9512266b8eaE233c8e7F0
0xa5C064a5928bE84Ca67cC585Aad1D15176C67AA8
0x12c1bF6D38465074867318Cd77129C1129859b09
0xeB0Ad1099f5E12968d41C04f8A22e6DBb0F65702
0xaA53378CbD262E717356EE3eb1ceb0A9AF6fEf7F
0xb56B7702fAC4e2Bcd5dA43Ede86705f2d52d708C
0x3E1Be7e1CBe471778bD5D6cb00094F7A0743EC9b
0xe7481EE7AF22f443303572CCCF28A4A73a21BBe7
0xb9eDB7355BF63a07353e3942cd4A7FC93c34148F
0x002A020e87FBB5A1D0eD67fF1dB5185f3dbf97EB

# Reasoning

All these 14 addresses got **same balance** and **same tx's** of **same value** at the **same time**, same behavior on different networks.

Attaching first 3 addresses tx's on Optimisim and Arbitrum Network. We can clearly see that everything is literally same, which is true for all the 14 addresses.

0x3211f9eAb94b9656EEB91015875187Fb44Fc1009
![image](https://github.com/connext/community-sybil-reports/assets/100838740/d06071d0-1264-4283-b291-544aa1a449da)
![image](https://github.com/connext/community-sybil-reports/assets/100838740/52356183-49ae-436a-aca5-0f6bf2ea732c)

0xDdD90053B6aAf9f2Df5C518158D09771Fa995C17
![image](https://github.com/connext/community-sybil-reports/assets/100838740/1b1edfee-6927-46f4-9793-ed9c20815f28)
![image](https://github.com/connext/community-sybil-reports/assets/100838740/48daec2a-1588-4fe4-a5ee-c20646acb044)

0x6B53f1A084572BdD09A433F06AfFFf0e35d81Ccc
![image](https://github.com/connext/community-sybil-reports/assets/100838740/111c3048-9bea-4cd1-b1aa-4f8cee4513c3)
![image](https://github.com/connext/community-sybil-reports/assets/100838740/b8d326b6-6f6f-468f-aa62-0992b3f578e1)

# Methodology

Used https://dune.com/KARTOD/connext-bridge-activity-and-top-30percent-depositors to find people with same [Connext Optimism LP - USDT](https://dune.com/queries/2466979/4057927).

![image](https://github.com/connext/community-sybil-reports/assets/100838740/750dcb93-db05-4786-bc7d-08ab70b139f7)

All these 14 addresses literally got same balance, same tx's, same lp and everything at the same time so clearly bots.

# Rewards Address

0xbBb816d9b0886e4b4F6e38996deB635D5bA77A8c

# 3
# Related Addresses

0x7d215BceE8782Bab1FCbd75905811B99AFa08c77
0xF882298e4c174f844743DbdB8e3fd3672087215a
0x017899418BF3F303a942ac7B1d6cbDE1023F7725
0x30fAE6e730975F7DbA9C826b1DCEC2989D14f1B8
0x9F1E13f821178Fd4f7391cC12BA6213E71241A5E
0xB3b5eF9003876Ec1Bd7f02b96c9c5b8501407aA0
0x46503A7823589107ACC6960D659F7026D9EBA0d9
0xDb442122D940ba1962512060790a9A09Fbd2aCC5
0x2375Aa302EB5Aca72Cd6f54dAe21090C0153093b
0x188f4bFed8aA0CF58cF13756E780c5A7628FeF43
0x02E9782c01825ed6780e9A7AeD02dE598783bBB5
0xB2d31077cbD1102eC0A61E9Bb0F76D5e9c9262ce
0xA5A1FAFf68AC42d3163F9CEa33b7c6e4C94325CB
0xA59792B780820ceb1a66b28a44424b2996A794DC
0xca1d884572811f9c2E7F652424c2CddD6F4CdDC4
0x710893552294a1F0A63c726396d0d05F74e1452b
0xF8C38DE3D6119A855345cfDd72cdA564DF9177D1
0x26caAC43B24758907e0641433C06C117419F15Ca
0x894360b4eBE843c48FB4db63Ec979D0B585e762b
0x8057137261b3566b76AeAa01A2dB67B9f686ab4D
0x35dbE8fc94F4c54543C845664BF7BB771BcDFaCa
0x4e4f32c18969680a65E6f421EC3145bFC1242710
0x08d8f275F7209eDbf112e02f981269c0f9B48f98
0xE31291bF8D7e65860A7E4b3E25b8F9c159A72006
0x11EfFeAB38475dbBE6FB5b1f36bfFEf8f301b559
0x4d7A8af8fCeF67Dfa40b963cff921c56a17AE484
0xEB2e7A04756C91cD7de48713C7bbC79B82Eb68F0
0x6E00262cEF0fa65a49bc5F8bc6e3d4d58b90C306
0x0faE962AE6356eD6173dC3A4e78612322A9563cd
0x76a58cc6C524d988F13Da460a26Db07Ed18604CF
0xd4dA7dcD484B64C3B335645Bf110F1B98B941ee1
0x4c30864e19c0910c4D8760ab21E90369b23C97C9
0x8a275e3674a571E50b8a0a5062095E13E014f3d8
0x54fE95dEA66886F00d47BfA34Ec04667b8309A0E
0xd62672132a8cb575Da1BC4d1079dC27679898BCA
0x31f99C90a21711f822F2Cf82fE3Cc6cFCA81f6A4
0x5E7DcdfEDDC1fA4A129e05127E7AabCE9b806032
0x680A444B058FD4790D320AB260729649b8034D7F

# Reasoning

We start at address 1 with balance 0.23385759 BNB on BSC

**Address 1 interacts with Connext Contract TransactionManagerV1 | 0x2A9EA5e8cDDf40730f4f4F839F673a51600C314e and sends the remaining BNB to the 2nd address, which does the same and sends the remaining BNB to 3rd address and so on for all the 39 addresses**

**So this same things happen with 40 addresses in a line, out of which 39 are in the airdrop Eligible List.**

# Methodology

I checked the Connext Contract on BSC TransactionManagerV1 | 0x2A9EA5e8cDDf40730f4f4F839F673a51600C314e for similar balance interactions and found out that the above 39 addresses have same balance and pattern interactions with the above contract.

This was the pattern on BSC.

**Received funds from Previous Address - Interact with the above Contract - Send Remaining funds to the next Address**

This happens linearly over 40 addresses out of which 39 are in airdrop list and are reported here.

# Rewards Address

0xbBb816d9b0886e4b4F6e38996deB635D5bA77A8c

**Comment by unrealxCode** [comment] 2023-08-25 15:48
# Related Addresses

0x3211f9eAb94b9656EEB91015875187Fb44Fc1009
0xDdD90053B6aAf9f2Df5C518158D09771Fa995C17
0x6B53f1A084572BdD09A433F06AfFFf0e35d81Ccc
0x98FC6112749f7663CC537Ca3330af68109891c09
0x3c9b541D0317276A05b9512266b8eaE233c8e7F0
0xa5C064a5928bE84Ca67cC585Aad1D15176C67AA8
0x12c1bF6D38465074867318Cd77129C1129859b09
0xeB0Ad1099f5E12968d41C04f8A22e6DBb0F65702
0xaA53378CbD262E717356EE3eb1ceb0A9AF6fEf7F
0xb56B7702fAC4e2Bcd5dA43Ede86705f2d52d708C
0x3E1Be7e1CBe471778bD5D6cb00094F7A0743EC9b
0xe7481EE7AF22f443303572CCCF28A4A73a21BBe7
0xb9eDB7355BF63a07353e3942cd4A7FC93c34148F
0x002A020e87FBB5A1D0eD67fF1dB5185f3dbf97EB

# Reasoning

All these 14 addresses got **same balanc**e and **same tx's** of **same value** at the **same time**, same behavior on different networks.

Attaching some example tx's of some addresses on Optimisim and Arbitrum Network.

0x3211f9eAb94b9656EEB91015875187Fb44Fc1009
![image](https://github.com/connext/community-sybil-reports/assets/100838740/d06071d0-1264-4283-b291-544aa1a449da)
![image](https://github.com/connext/community-sybil-reports/assets/100838740/52356183-49ae-436a-aca5-0f6bf2ea732c)

0xDdD90053B6aAf9f2Df5C518158D09771Fa995C17
![image](https://github.com/connext/community-sybil-reports/assets/100838740/1b1edfee-6927-46f4-9793-ed9c20815f28)
![image](https://github.com/connext/community-sybil-reports/assets/100838740/48daec2a-1588-4fe4-a5ee-c20646acb044)

0x6B53f1A084572BdD09A433F06AfFFf0e35d81Ccc
![image](https://github.com/connext/community-sybil-reports/assets/100838740/111c3048-9bea-4cd1-b1aa-4f8cee4513c3)
![image](https://github.com/connext/community-sybil-reports/assets/100838740/b8d326b6-6f6f-468f-aa62-0992b3f578e1)




# Methodology

Used https://dune.com/KARTOD/connext-bridge-activity-and-top-30percent-depositors to find people with same [Connext Optimism LP - USDT](https://dune.com/queries/2466979/4057927).

![image](https://github.com/connext/community-sybil-reports/assets/100838740/750dcb93-db05-4786-bc7d-08ab70b139f7)


All these 14 addresses literally got same balance, same tx's, same lp and everything at the same time so clearly bots.

# Rewards Address

0xbBb816d9b0886e4b4F6e38996deB635D5bA77A8c

**Comment by unrealxCode** [comment] 2023-08-26 06:43
# 4
# Related Addresses

0xE17E65e1F414c6dE754c220fC7984508B3b8d453
0xFe36305906676f3952cFc29c6f30f3aFcB8d304E
0xA4Bb074B3486f3816De50579BCa94cc011C05e80
0x783D1350e34e55E9d7a67AE8cC6B3E0Df83c6879
0x454BBa8FB3b67Aa08201340d641604905AD046eb
0xCCf66168433C67B0Efd1c9f86939ceA5d206ABc9
0xB23dF8815dBbFEF35e6c4586d9fA67a271B6EEcd
0xC07caAAc5fd4DCE68d894fB009d85F39471Eb804
0xae609e47Ccc60862C899c4D97e3aFc0C8b94AaB9
0xa024325eD03170a2A6f571f5E25022925E699c9d
0x50764E9633824E285608989a802eBdEFEFa79Ef6
0x61AEDB2eA21aDfDdB032df835d2FF02F0dA68C66


# Reasoning

**Address 1 funded Address 2,3,4,5 and 6 | around 0.005 BNB each on BSC at the same time**

![image](https://github.com/connext/community-sybil-reports/assets/100838740/52fc81a9-1134-4de4-8dc7-859ec7e32782)

**Address 6 funded Address 7,8,9,10,11,12 | around 0.0055 BNB each on BSC at the same time**

![image](https://github.com/connext/community-sybil-reports/assets/100838740/16f12120-af59-400d-ab2a-aa3a8c8fce38)

**All 12 addresses interacted with Connext Contract TransactionManagerV1 | 0x0D29d9Fa94a23e0D2F06EfC79c25144A8F51Fc4b Fantom Chain on Dec-07-2021 in a duration of 4 hours.**




# Methodology

Checked the Connext Contract TransactionManagerV1 | 0x0D29d9Fa94a23e0D2F06EfC79c25144A8F51Fc4b Fantom Chain for similar balance interactions and found out that the **all the above 12 addresses interacted with this contract at the same time** and all the addresses are funded by 1 **Parent Address with almost same amount of BNB on BSC**. So 99% probability that these addresses are controlled by same person.

# Rewards Address

0xbBb816d9b0886e4b4F6e38996deB635D5bA77A8c

**Comment by unrealxCode** [comment] 2023-08-26 06:43
# 5
# Related Addresses


0x03F8D481BEcf0463BF1f201feCF4095503730267
0x9E9E7F7C3a3849AFbf4D6302E7698bb139dC1371
0x2B60F64201d99282A19beb47c455627960395598
0xD117691943ff00EcdCC8B446E6653444B4b6672b
0x6d2742b2CcB325AA854cB2648a0841655a7c9C22
0x026b6e0FFdf858C0FB1b4AcB73591873ac9DA472
0x2Ef15A729D9a64Ca966aEe408675c11fF0e2D757
0x3d1C2F7e32A16E638daa809CbfA697D4Fd76F2c2
0x0b148b0D0838A9abd30F9cb51Ae2dd6A7C3cDFD0
0x3c4dC448C8372CaaB97d801058A1d5f924E2b234
0xd27883A7e5F4A07C8993330E6A84E0913e712A9e
0x57fc06b7c478D797C8b8a15fdFf1124aF3d27A07
0x58a47116F29772aE355917fB957d2434281eaf35
0x7E4E2451E4C20Ec09eCB2Ad1b2506DA0f9e922e3
0x0411c806d9CCa957BE048bd3925a5a9fB13614Dc
0x50001b34B636Feb9C48972959187394c70acf888
0x2669A58a1af7B06FeE45bDCb608d634486ABABC7
0xD7Cf321496361065bE752409D1110e29Ac5E6bD7
0x40Ee90594AD06fDDC823f6F2c56eFcD8D3EC2f96
0x568290Be503A6b51057d81E4BCBbE7D1943F0d82
0xE23016a6f3B6a8C245204340A1b78E961A730B3A
0x2e04bebf69bE38f12F9035333FEF1Ad51B49482E
0x5c1abDb18a157d7FCB10FD8A08b54a6579B1DEe9
0x32b2af57A312cEA3fFb2032215Ffb88fEBa97377
0xec9e49ffe7da09F91BB53b904247bEdb163B3828
0xc998f3e777DaD21D49FCc3B0b6268E3973C658Cd
0xC3C6cBE315Bbd3574c0E5edEe0B16d8ADB9EaFF9
0x6f0378949B0Ea943268d66369d99098AD17fbD11


# Reasoning

All the above 28 addresses received 0.01 BNB on BSC each from Parent Address 0x76A81325E0bDc64d5F1e28EcF8f6881CBe32Cd20

All the 28 addresses interacted with same contracts like TransactionManagerV1 | 0x2A9EA5e8cDDf40730f4f4F839F673a51600C314e after getting funded.

All 28 addresses receiving 0.01BNB on BSC from the Parent Address at the same time Oct-01-2021 03:20:08 PM +UTC
![image](https://github.com/connext/community-sybil-reports/assets/100838740/d9924161-60bb-48ab-9d74-e782de966a26)
![image](https://github.com/connext/community-sybil-reports/assets/100838740/f9286a80-d2ec-474a-a46c-7fda1521b35d)

# Methodology

Checked Connext Contract like TransactionManagerV1 | 0x2A9EA5e8cDDf40730f4f4F839F673a51600C314e for addresses with same behavior and balance and found out that all the above 28 addresses were funded same amount from same Parent Address at the same time. So 100% sure that its a Sybil cluster

# Rewards Address

0xbBb816d9b0886e4b4F6e38996deB635D5bA77A8c

**Comment by unrealxCode** [comment] 2023-08-26 06:43
# 6
# Related Addresses

0x3e952dFd6698c7D6313c4726a10dd369246687c8
0x65058265E1dd1e1cA842579587F41CBCDC14bd76
0x5D6B0bA49f94D92e60aCC2e46f981835fD9dE00c
0xA94Ab8A3784FfeA9A2E126a632a0bbB934b06657
0xD23f706Ff1674c6c87599BeB888Cc61797d7c7e5
0x6781e93A2701c5215552634ac13788C7Fe319dC4
0x1f5D78e120F29F0781ff00D764B72049dDa279d6
0x61821d272c3B9a4d8F800F52B9CAFbE18e7c8299
0xf40D626096007d56B8cD231b478fDEC0725992D7
0xcdE0019F9A653F7686C30884e29d0bF7e6dc365A
0x5eBae21FBC06229aE10f1E4c3a276a2f674cad97
0x830265a911Bf91e3bE98B01B911314e704A62855
0xBA223d69b80DC1c03389ddBe5cFD7452476027be
0x6E68f7b51255Bde0af11C4188F2E7C7cAB9664E8
0x6726E863C99161D9C8B941624c8067F9Fa943426
0xE459eAa50ec6EB38fAB08A0c1BD7D4989D5e8106
0x9E23012E9CEabc76FCebf488cff029A4b5A02834
0x979eDC7441900b28a51EB8D54834271685B141CC
0x5D344f646B395eDb50d536e41AC98f7FD1a576F8




# Reasoning

Address 1 to 10 received 0.1 MATIC (Polygon Network) each from the Parent Address 0xd3a2d421c4f4ad90e191bb5ef36b58d76d52ea94 on Mar-21-2022
![image](https://github.com/connext/community-sybil-reports/assets/100838740/1d822dd8-835b-4691-9b08-aa0edf91d33b)


Address 11 to 19 received 0.03 MATICH (Polygon Network)  each from the same Parent Address 0xd3a2d421c4f4ad90e191bb5ef36b58d76d52ea94 from Mar-24-2022 to Mar-25-2022
![image](https://github.com/connext/community-sybil-reports/assets/100838740/cbd431d7-4f7a-40fd-86c7-e90746e69717)


All the 19 addresses interacted with Polygon Connext Contract TransactionManagerV1 | 0x6090De2EC76eb1Dc3B5d632734415c93c44Fd113 right after getting funded from the Parent Address, and all address got almost same number of tx's with same contracts.




# Methodology

Checked the Connext Contract TransactionManagerV1 | 0x6090De2EC76eb1Dc3B5d632734415c93c44Fd113 Polygon Chain for similar balance interactions and found out that the all the above 19 addresses interacted with this contract at the same time and all the addresses are funded by 1 Parent Address. So 99% probability that these addresses are controlled by same person.

# Rewards Address

0xbBb816d9b0886e4b4F6e38996deB635D5bA77A8c

**Comment by ArjunBhuptani** [comment] 2023-09-02 01:40
Cluster 3 is duplicate of #261

**Comment by unrealxCode** [comment] 2023-09-02 17:11
> Cluster 3 is duplicate of #261

wait I think my cluster 3 was before https://github.com/connext/community-sybil-reports/issues/261 ?

**Comment by ArjunBhuptani** [comment] 2023-09-02 22:41
Cluster 1 - invalid
Cluster 2 - valid
Cluster 3 - valid
Cluster 4 - valid
Cluster 5 - valid
Cluster 6 - valid

**Closed** 2023-09-03 02:45 UTC
Labels: pending application, ts

**Comment by A-Keyboard** [comment] 2023-09-03 18:05
@unrealxCode Can you dm me on Discord, my discord is khlilo

**Comment by unrealxCode** [comment] 2023-09-04 16:04
> @unrealxCode Can you dm me on Discord, my discord is khlilo

BXF3J74G
