### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by sybde** [connext/community-sybil-reports#38] opened 2023-08-24 23:58 UTC
# Related Addresses

>
0xD08267cE370BE8074FcA61f2ee855C78b0AB910D
0xec911027C5956C4B7e3b79B06c0D107b3a003F1F
0x1d9D739004473c231cd08111bB5dd5E7c082dCd4
0x2C382DAe1a94D689BEcf78eDBEB1900C46f75ca2
0xDfE9e837A7BC21b0c928066e471E542fF75d3831
0x1690C3435802CA8482F76ecFc32158b345057649
0xc5263403C4B068e0efaFa3463e08e40F8aDe391C
0x1eA05E66559c497b7d786a3F657BaA5ba7FE0Bc3
0x3d4f2F2feb4963BdCC0cd48d6e2B57806c3F2ff3
0x1f27F86dBB71F47222ccb50F8A19acE82cDf29b4
0x470169600E08c6733cBAfeeEdeF1352f4738B0C7
0x0715B21A1f43C80CE41daCb7E1Ea89Aa8fe3FC2A
0xF0a9dA8cc27830D4a7Cc9Da49a18655371653321
0xE6d36Da02583C1acD79FFC7065f6d9BB1e8a6C30
0xaac2F9d9D26c7CDD9b8d2cca67a08323E525F641
0xB18Af22479F14F26487Aa6354dAD7D7CBcd527F1
0xCB8189bcF385867Db54E72c390472D646A448003
0xC218E61C2f6EDe9bfdb504f85BDf8802CBEce31A 
0x5dF9576b0C6441F69809Ca510685C01F09DbA1e9
0xC2B1FAA0a2615C6e315596dc6CbE3c1049C0aA0F
0x00493ba4E1864aCd75e2d76D7B6F4E6593615631
0x53716f7fF7949e06AfaEED5aA169cA31E53d7d46
0x503d17563769a941f9c877966790C389053F79A1
0x71254Be0AF9f5522425C75A2dD1C0fC42162655F
0x63ea96398ffCaC3b4BEdE15DE824468328E3BC45
0x552F386a3C6fda19eB75AcdE84f013dF69a7006e
0x9542495bBE11840eB64287f73aC78DA61C837714
0x0A26c375EE357dfB67441871dDec53f57FFE6d65
0xA2D8425A38fAD12058519c0d334d89172AE42D2c

<!--
Provide a list of related addresses that are currently eligible for the Connext user airdrop.

The list must contain at least 10 eligible addresses at the time of review or it will not be considered. The eligible address list can be found here: [TODO]. Reports will be evaluated on a first-come, first-serve basis.

Example:
```
-->

# Reasoning

All addresses received funding 7000 usdt in arbitum from the same parent address 0x0161eb3bE364eaBBbcf5C8E59A3A989AB03E77d5 in same time 28.05.2023 between 07:28am and 07:36am After funding, in same time 7:30 and 7:50 each addSwapLiquidity on connext. 27.06.2023 all remove liq and withdraw funds in all adress 0x0161eb3bE364eaBBbcf5C8E59A3A989AB03E77d5

-->

# Methodology
I used the service https://platform.arkhamintelligence.com/
He pointed out to me the connection of these wallets with one other from which funding was carried out, also by visual inspection of the transactions of these wallets, a coincidence in time was revealed in the conduct of all operations.
https://platform.arkhamintelligence.com/visualizer/entity/0x0161eb3bE364eaBBbcf5C8E59A3A989AB03E77d5?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1

![Screenshot (14)](https://github.com/connext/community-sybil-reports/assets/143136925/0e553f5e-216d-4e93-9f2c-978bee70a1c9)

<!--
Explain the method used to discover the addresses and provide proof that they are all related and likely operated by a single individual/entity with a high degree of probability. The methodology should be easy to verify or the report will not be considered. Please, also include links to any additional materials you’d like to provide like a github repo containing the script used to uncover the reported addresses.

Example:

The reported addresses were discovered by checking irregularities in the number of bridge transactions made via Dune. The resulting addresses were analyzed to find repeating transfers at standard intervals and sequence.
https://platform.arkhamintelligence.com/visualizer/entity/0x0161eb3bE364eaBBbcf5C8E59A3A989AB03E77d5?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1

https://dune.com/queries/0123456
https://github.com/airdrop-hunting
-->

# Rewards Address
0xd52bb9d212eE0941Fe375D569D67e7Ab7d8d1C9F
<!--
Please provide an address or ENS name that will receive any rewards earned from this submission.

Example:

-->

**Comment by ArjunBhuptani** [comment] 2023-09-01 01:15
Duplicate of #12

**Closed by ArjunBhuptani** 2023-09-01 01:15 UTC
Labels: duplicate
