### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by hongtham4** [connext/community-sybil-reports#136] opened 2023-08-25 10:56 UTC
# Related Addresses

FROM | TO | GNO-HASH
-- | -- | --
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x26086f313eaa5b07115ad656794381caf868937f | 0xee41603ddb552af511a617396936282e041a478faf6af0c954c355ee2c18832e
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x75d9a5138dca783148013ad275903413b6bde73e | 0x7a0d062741574756dcc41160d7a5908ec1c892d91478ee82388e393ae1f3d084
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x2811a79186633124e7b1b5ba0f2a6a82908ad2e6 | 0x5379340550c226d6a31278626ee2a87418e4ec1f88ee869b05437977e59d4198
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x297bc07ffaeb4f910bbc17f35eeb1d2af7fc8d25 | 0xe7dc3dad7dc5e787685941533e17c157ae9c8698778ccc6d31c2ca0ecffbb9bc
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x808510ac74b07e1856aaee83d47b1101b72f2857 | 0xa2d7f113609df5c2aa219b799a03816f3c945b86c854bd511560fca7be3a35ea
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x822fcee5b610d90724a20a077c466a323cefc41d | 0x20dc0408a695be9f3d64becb69871c9b7833b8ef9b59f6684921809ecb1da76f
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x3b403b1e02cbb87b67feb47f9e217fb304e89ef4 | 0xdb7fcc20b4e3721a3b42ca82f0c96b0f60341d6ba353a97db723cd9147aae17c
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x3f60e60e2281b81fd20922c2a250106324876e05 | 0xfb2c22f4fd9542e3865289c61536925c89181a6b17e5028d1f690482ff9177f5
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x90449285bb5880c25c43845b67ff5d71c1ed291f | 0x70aba6133caf261647a0aeda9ffbf21e3989f91a0acd659008be95630761d30b
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x45bf71c5d41dc9fa871977503ecd12d866cd602c | 0x043664ba123bf18d61cb0583dea1a63a140afc55e310c980644ba64236120f99
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x4790353cdae1c8caf0c8d7fe34dcb0c3c6651c45 | 0xcbbc9bd057529d25be68bd90cfe0064a779971856c82063c965d2d34c45d015c
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x97537c457d7d6f185f2699044d1df6be2d04780d | 0x4fd6069e83fb105554c6ced5b5ea4ac2cd3a861dc97800f5c78cece148d9d7a9
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x4b0f87620f80ce3e0bb0187ba960537e6dce50ec | 0xf17558f17e3593caf18fc8caf5287c6af269f7c075e3007c0a0438f1b7eb5a51
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x9b7b8af90053b6efa2279d34d0d6f918f3eb79b9 | 0x1b65aee0fcd0e0310d13cb99f37b498c76297255fd13ed990f5fcb17702a3672
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x9e05d6382f5bca6e433a0cf6150327eaffe97fc2 | 0xfe78542945605c865f8ee6fc629c9380fac12192f9f87a9779506a00725dd8c4
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xa292bfa2a616724a10f75941d063e0215744b493 | 0xf7e833766c6edbb703721f773f88b601d7f652ba9edfab5a7eea45dff104c7d9
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x069b1bd7be330591f28e9f954f1d889a349a169a | 0xb334850d18a9c1444885073abcc38eab185e86b1da083b3590d34b36294eb5aa
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xa8743b72dce3e49c2b852d6586f22fa0494eb9cf | 0x7c793b683d3f635d755ff9fcc89fe17e1428f7ee794b6f795ba832de05ec4037
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xaa7da4bce82add68b2e9e86e75983a0a08af81e4 | 0x8f40ef6164caf56d5ca91de90d4c80eca01b72c3e94130b67f24aaed618946ed
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xaf9bac4a530c6cbbdba05de8d65d859562b5c42c | 0xa15312aac45e95b77d774ab7b9ae48ef0f86cc9073ab2db7d17d75b80c41affa
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xe009b5c3c2ee793c4530b24c38678e22ba23eb2f | 0x5896ee6dc10878460a4f2ad4be66405790a298cfe8e5dca524edf0daa67e2683
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xe1ec61164bc98edb77dc8f9ec6d81f5b3b4ceb73 | 0x72764f177d6523a3d0a281fbaa049dd249e20507da2f65e5f3d47a5db9480080
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xe30abeecd8c4efdbf94ca1c02e34de058558aa2c | 0x71c102b730f5356997e4d8aa781e14dbf2b441d97c20b1f9ac9da97ece5b4f41
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xb53f10b3f80a687331eaea58d8f2e8010df2c3a6 | 0xdb6b4bf0f0c89ee5b85ed64b501da1a8ff585f24400760ab9f822b798ce93d49
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xb77ab1eadde4c0d34e59d528c9d32ef3f357e3ae | 0x3d81176060478b6ba2036fe3ac984574c898ee85b1811f0275ba1cf579c0f245
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xe8fe6a24448dd4ef181b1538732fd32b1b3e2a47 | 0x09ad2afebb67dd7cff4054496dc48719b8242cd91ad78ed4b2f5ccb24544171f
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xee5666cdbf0827c9d9b8361c52dfe93efeccbd0e | 0x7c3581e09c37c84ec8a59c9e64d4ce5fd2e2479d9e0e3bc4355ff42da23efa13
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xef1526370883fbe13803b6fea6d57125e07ee169 | 0xf74d1ec9b5f42b3662e3420d6fcc2a5e8692a26d232123d3b827db734a2fa77a
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xf4487021942c94ab684e96a47536a3511b5875c9 | 0x956330c849f691e0b14d9247a7a2445a1f01d0cde94f7cf8195897e798c48c21
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xc8b9c830d6b7c207cd0556c5f5e94ae5cee3e1ed | 0xa0f3749a01c3258cf6b698d17ae615d048151f54d8d03f10030bba14aba5471f
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xc9d880b9e07bba82cf674ac756f68570c668f80c | 0x505015e3749f92d157d60ae13b69efb8ff25d4b3ce74fbf381060233bc47138c
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0xd07935c93994b1c92ae9068ad9775af7d4015a59 | 0xef91526023576b7686902bddeb5cbd2ff0ecc2ddf8a23751e962431d5e3df649
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x06bc2ca2db6560840cbf94d43f31c2e5a514b9e8 | 0x362f032420eababa56d58954b878efe0ff03a98ad1215ad04a6fb66645d33513
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x08a727a1d5eecb23ea9dfd7e12c37ae1e1a2a97f | 0xe1d0753075c8d18f93784b82895d2d030d26db85a825d9993fe660dfb3a4d78f
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x5c395aad37e3dffabfde4d3e16eb8d3c9e8350c1 | 0x4a968279c346668fe7210bf771ff2348de4daede9175280ccf90e467445011c2
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x1b6585aefba196a927910ee3f45f0810c38dca5f | 0xcad04a0564df44531bd5fb153a8402dbcd8014bf8c14841401b5425b6feb6400
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x1bf32e0f147400f20d185de8a65881a6bea41e0b | 0x9c38d7c56d42d90750a48551e23ddb3f85a2a10a2a304bce086fe769f8c63184
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x6e7b42a8f91420000ea47588ff38aff483ce4811 | 0x56e482ac4cf34f79b1914f4eecff385cdfd77b89bb21a92785e62a9f687c43a6
0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b | 0x2391664d62eddacee8aba4dfec6c2ce3d2ca0127 | 0xe527f7cb5938cfae1ff415af989eb4dadf4be8f75d24c971a36c214ba659638b

# Reasoning

1. Table description: this table shows the first set of hashes for the address and sender of this sybil attack.

The sender address has a very small number of nonces and is not part of an exchange, but a private address.

Because it is the first time these addresses have received a network token from this network, it is unlikely that the address has been intentionally contaminated by someone else.These would also not be mutual transfers between friends.

![image](https://github.com/connext/community-sybil-reports/assets/143180414/b0d59deb-0724-440b-be26-929d8c60b235)

2. Sender (From) Addreess : 0x9dc48df5ef69dc518ba1d868b1e37ae79893ec6b 
    Time : Mar-21-2022
    Value : 0.01XDAI-0.05XDAI

3. These 39 addresses have the same on-chain behavior, use Gelato's contracts on polygon and gno-chain, and quickly transfer funds to the next address which has the same on-chain behavior.

About 527 days ago, these addresses received more than 1,000 USDC from the contract, divided into 5 times, each time more than 200 called the same contract, and then received more than 100 USDC once 507 days ago and quickly called the contract.

I've taken some screenshots:

https://gnosisscan.io/address/0xc9d880b9e07bba82cf674ac756f68570c668f80c#tokentxns
![image](https://github.com/connext/community-sybil-reports/assets/143180414/ec66e369-2568-48a6-9861-3ced8f7c05ca)

https://gnosisscan.io/address/0x4790353cdae1c8caf0c8d7fe34dcb0c3c6651c45#tokentxns
![image](https://github.com/connext/community-sybil-reports/assets/143180414/ada760eb-4000-48cd-8682-969d5b9d0eb6)

https://gnosisscan.io/address/0x1bf32e0f147400f20d185de8a65881a6bea41e0b#tokentxns
![image](https://github.com/connext/community-sybil-reports/assets/143180414/c866904c-f8c2-434e-8d35-e4d57d74cc3d)

https://gnosisscan.io/address/0xa8743b72dce3e49c2b852d6586f22fa0494eb9cf#tokentxns
![image](https://github.com/connext/community-sybil-reports/assets/143180414/80d33d8e-0ea4-410d-b7d2-679758eea233)

https://gnosisscan.io/address/0xd07935c93994b1c92ae9068ad9775af7d4015a59#tokentxns
![image](https://github.com/connext/community-sybil-reports/assets/143180414/b8fcf6d4-6919-428b-909c-b927f17f4ba5)

https://gnosisscan.io/address/0xa292bfa2a616724a10f75941d063e0215744b493#tokentxns
![image](https://github.com/connext/community-sybil-reports/assets/143180414/7387f17c-9495-4692-b99e-e716f1bc6f09)

5. These 39 addresses currently have almost no money in their accounts.

# Methodology

via  'https://api.gnosisscan.io/api?module=account&action=txlist&address=%s&startblock=0&endblock=99999999&page=1&sort=desc& apikey=YourAPI'
Find the hash of the first money received for all addresses in the gno-chain, count 10 clusters of addresses with the same from address, and find their correlation.

# Rewards Address

0xFCDDF1BD37cabF95442fa587e3387100Bae108Bb

**Comment by ArjunBhuptani** [comment] 2023-09-02 02:04
Duplicate of #133

**Closed by ArjunBhuptani** 2023-09-02 02:04 UTC
Labels: duplicate, pending investigation
