### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by luswetiharon** [connext/community-sybil-reports#415] opened 2023-08-26 21:26 UTC
# Related Addresses

0x899eCd6B39D41377Edb3f792ebe08151e3d03Fe1
0xaFCd7A1379b790EDB1445Cf671cC5Ae267CA9c51 
0x68E3AC873Ac6D335E28785D7EA9D88B6b5e220F7
0x63fDea6fc8d77145De67F83Ed883273039F42620
0xB3D4BF93Ac250a40dC75c5A4A9e41810CF73F47e
0xa5f3AE78d8ca4C74C12Fc38765cca0ff376d1406
0xaCc4E2C6a3caA987eAB786f00e6663E172180Af0
0xaf2947beB7bFD50f5Ea168d22c6d143796D3B209
0xC7cc21158Fda7b48a53A1F24F4C5C5B85654b447
0x35B3bcc8005d2477F4A1ec0e275FF1aAFF822cb0
0x206554017d5cc2743cEe23A5DCCcA2524989078a
0xB48978cbE537Ddd29752B300ee9143131324d0fF
0x561DB00a5D90E124A3E87CD6a8396633E7c26Ea1
0xBfb4a11A2247a013B50EAf5D68D5db1cc752c4A9
0xd3f81e3E5BaE2d61949efD4c2550Edf6D1a02186
0xFfD708c4aCa6d0D4335836b2Ca51576069418d3D

# Reasoning

The group of these addresses has one asset recipient 0x8eCB0D0b41920feAc91Df3179d5D025bc2B51fc3. These addresses have the same algorithm for moving assets to receive a Connext airdrop, used almost identical amounts, started free activity in Connext from May 12-16, the same time frame. The rest of all wallets was moved to address 0x8eCB0D0b41920feAc91Df3179d5D025bc2B51fc.

https://platform.arkhamintelligence.com/explorer/address/0x8eCB0D0b41920feAc91Df3179d5D025bc2B51fc3
![1](https://github.com/connext/community-sybil-reports/assets/118363912/c010cd19-0d72-47d8-88f5-93d67d57e323)
![2](https://github.com/connext/community-sybil-reports/assets/118363912/c0237a4e-18f6-4b9b-8a97-9bcea6898615)

https://platform.arkhamintelligence.com/explorer/tx/0x07d9fbb7f8d1f7334925cc324220c4e3a84b0c6419d48ad4cdbe2ea07516e2fa
![3](https://github.com/connext/community-sybil-reports/assets/118363912/d88583d2-30f2-4854-850e-4be20b4599bc)

https://platform.arkhamintelligence.com/explorer/tx/0x6856d2e45058710770f31de9c5610957914df3f8ad787a39e0d0eb1c85788938
![4](https://github.com/connext/community-sybil-reports/assets/118363912/21dc3e1e-1ad9-4d55-a080-e27a8e772e59)
https://platform.arkhamintelligence.com/explorer/tx/0x47502e748f1501a68fdd1b5e39f60b37d65c908008e663df543e4712a97b2189
https://platform.arkhamintelligence.com/explorer/tx/0xbbc5c2882588b6303383d8cfec48ccf9ba5efbeefb37358ba5856e4de5d5abcb
https://platform.arkhamintelligence.com/explorer/tx/0x3e4ea1ef555c515e3b2527cb00f504dbbcb0f1f381a7ed9128fe4aa8fa6b702a
https://platform.arkhamintelligence.com/explorer/tx/0x8d801115db71b2c97a3c9f964a28f352eb641ed5a562884ce31477758a5b2aa6
https://platform.arkhamintelligence.com/explorer/tx/0x7f9c88559db85c4459d1176cacd442392053043cb0083ad2e83c190ca7b04986
https://platform.arkhamintelligence.com/explorer/tx/0x8135801b1ecd71a1d1e9dfa83a490888c26ab916eb79e87ed2fc29287dd79602
https://platform.arkhamintelligence.com/explorer/tx/0xe901cfa67c3c10121bff298a586d637d0a5dbf3eff941bed84d3f6282fc4c472
https://platform.arkhamintelligence.com/explorer/tx/0xd9f421d079c60da6428b750037fc3c600fcf0d0a1c0a9db6bcc6118c28f4b3b4
https://platform.arkhamintelligence.com/explorer/tx/0x878af305ed551ef834b02fea282d02a5ed4cbec19e4a67935407b10b56f615cb
https://platform.arkhamintelligence.com/explorer/tx/0x5d44c4b473cfc801a37ae3ebd2c957496dcc1082382bea8de810dc9a4db2c698
https://platform.arkhamintelligence.com/explorer/tx/0x696e99999093748d1ae5f3456b34c77d1f44f0a5adb0f7cda63e55f76b0c8adb
https://platform.arkhamintelligence.com/explorer/tx/0xfc7a449b019ce85f5fb0e2f1efbddcc99c5434f996ccbef8d4973fa60a036133
https://platform.arkhamintelligence.com/explorer/tx/0x3e4ea1ef555c515e3b2527cb00f504dbbcb0f1f381a7ed9128fe4aa8fa6b702a

Accounts follow the same algorithm of actions for moving tokens. For example, several wallets from the list are selected. The last action everywhere is moving eth to wallet 0x8eCB0D0b41920feAc91Df3179d5D025bc2B51fc3

https://platform.arkhamintelligence.com/explorer/address/0x63fDea6fc8d77145De67F83Ed883273039F42620
![5](https://github.com/connext/community-sybil-reports/assets/118363912/ddfe38a6-84b5-4c1b-851d-73efefd7bef4)

https://platform.arkhamintelligence.com/explorer/address/0xC7cc21158Fda7b48a53A1F24F4C5C5B85654b447
![6](https://github.com/connext/community-sybil-reports/assets/118363912/2408abbb-5b8f-4739-9584-15ccdef8f337)

https://platform.arkhamintelligence.com/explorer/address/0xFfD708c4aCa6d0D4335836b2Ca51576069418d3D
![7](https://github.com/connext/community-sybil-reports/assets/118363912/d41d8d8a-3ea2-49d5-911e-c66d355e99a1)

https://platform.arkhamintelligence.com/explorer/tx/0x07d9fbb7f8d1f7334925cc324220c4e3a84b0c6419d48ad4cdbe2ea07516e2fa
![8](https://github.com/connext/community-sybil-reports/assets/118363912/8b36c07e-080b-4064-bb5d-20a60ea4e64f)
The time of the last transfer of tokens to the address 0x8eCB0D0b41920feAc91Df3179d5D025bc2B51fc3 and after 2 minutes a bridge is made from this address to Connext https://platform.arkhamintelligence.com/explorer/tx/0x57ec85405f09fa504f14d003f57b325c2dc5e7045c1017df8b519239d1f9cb08
![9](https://github.com/connext/community-sybil-reports/assets/118363912/e966ba88-c1a3-427c-9836-b3fb09ed4f7d)

# Methodology

All information has been manually verified through the platform https://platform.arkhamintelligence.com

# Rewards Address

0x9780Ee2BF2B7482eBd246cAa3fc1Ca04f9756cDd

**Comment by ArjunBhuptani** [comment] 2023-09-02 00:41
Duplicate of #133

**Closed by ArjunBhuptani** 2023-09-02 00:41 UTC
Labels: duplicate
