### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by SaintSilver** [connext/community-sybil-reports#47] opened 2023-08-25 00:42 UTC
# Related Addresses

0x915fB2B6628736f9ACF61BAb67D58E88b442C461
0xd0559788EF7d70aB7479A3a5C60A88240F06D6b4
0xb3781E01164eD345253673209eeb0CD2cd598f0d
0x3CBd0eeCf0DdCA602AbC6516951E96136B99ca04
0x915fB2B6628736f9ACF61BAb67D58E88b442C461
0x3642E77cc1Fabd0399aE20fD0F49b196b0855bF3
0x989cbD3534860166301Bb6e56c5d5fc40B4bDa45
0x6E91050Cf96D700545cF1b21Ab49005efb3Ab45B
0xE9505bC513d3E07F6BB0E932250F373921C12366
0xE2163435824eF43546E308b617130463494e4D61
0x679916d018663907e4f1b981c2826f8e8934be97
0x0ca2302affebddba4f42d3d7c47089b2c73bd6d7
0x5f21973f8ff9fbbc624963e45b6b58ed36b36245
0x037e154dd747790830fd772681044a71671e0db1
0xd29b8fe7e0de10d15b2554f7cf81e48a86af520a
0xbeae689b7bdf89d140163263ca490c95fe778d11
0x2120e8aa77916ce90d08fa8c7b1ce6c8079349e4
0xc6a0ea88a426aa3bacf802a5cd076487516e1e10
0xd48057532910a0da53a27204e2afb96c82f2ce74
0xf9b9610a88f83c745978d44feebb81ff259efc30
0x5b002b5408e09f5b5051db68b7c149a409c86e01

# Reasoning

All addresses received funding from the same parent address `0xf89d7b9c864f589bbF53a82105107622B35EaA40` (bybit), 
And they all received the same time, 0.11eth. (23 Jun, 2022 08:23:13 UTC) 

And In the connext arbitrum (DAI), he interacted 3 times with same amount.

example:
https://arbiscan.io/tx/0xc8a9a02a524484e7305f60602fbf2ae57bdc1a0d0da21cb1c4ad6d482abb2a68 (May-16-2023 08:51:12 AM +UTC)
https://arbiscan.io/tx/0xe3d49f46d615e450c5971ae5f3392de420b6cbc285775c5a24fb467e83431263 (May-17-2023 11:10:24 AM +UTC)
https://arbiscan.io/tx/0x5497aa045400d849e2583b6316cf13a7483da4432db653125599b078d942e553 (May-31-2023 07:34:14 PM +UTC)

# Methodology

I found it using arbitrum scan, 
and arkham's visualizer, which can be found at the address below. 

![photo_2023-05-16_18-12-30](https://github.com/connext/community-sybil-reports/assets/32532788/3f5ca4d4-4a76-41f5-8cfc-c6220a8759b3)

![aaaa2](https://github.com/connext/community-sybil-reports/assets/32532788/d6a96f82-5755-405e-993b-e6849bcf9de7)

https://platform.arkhamintelligence.com/visualizer/entity/0x915fB2B6628736f9ACF61BAb67D58E88b442C461,0xd0559788EF7d70aB7479A3a5C60A88240F06D6b4,0xb3781E01164eD345253673209eeb0CD2cd598f0d,0x3CBd0eeCf0DdCA602AbC6516951E96136B99ca04,0x915fB2B6628736f9ACF61BAb67D58E88b442C461,0x3642E77cc1Fabd0399aE20fD0F49b196b0855bF3,0x989cbD3534860166301Bb6e56c5d5fc40B4bDa45,0x6E91050Cf96D700545cF1b21Ab49005efb3Ab45B,0xE9505bC513d3E07F6BB0E932250F373921C12366,0xE2163435824eF43546E308b617130463494e4D61?flow=all&from=bybit&positions=%7B%220x915fB2B6628736f9ACF61BAb67D58E88b442C461%22%3A%7B%22fx%22%3A13%2C%22fy%22%3A-53%7D%2C%220xd0559788EF7d70aB7479A3a5C60A88240F06D6b4%22%3A%7B%22fx%22%3A18%2C%22fy%22%3A35%7D%2C%22bybit%22%3A%7B%22fx%22%3A-70%2C%22fy%22%3A-12%7D%2C%220xb3781E01164eD345253673209eeb0CD2cd598f0d%22%3A%7B%22fx%22%3A7%2C%22fy%22%3A-13%7D%2C%22disperse-app%22%3A%7B%22fx%22%3A128%2C%22fy%22%3A-14%7D%2C%22layerzero%22%3A%7B%22fx%22%3A122%2C%22fy%22%3A-8%7D%2C%220x62331F1D2e5a3802aB6a58c1faB19b01edE94abd%22%3A%7B%22fx%22%3A136%2C%22fy%22%3A19%7D%2C%22hop-protocol%22%3A%7B%22fx%22%3A117%2C%22fy%22%3A-40%7D%2C%22space-id%22%3A%7B%22fx%22%3A145%2C%22fy%22%3A-11%7D%2C%22stargate%22%3A%7B%22fx%22%3A182%2C%22fy%22%3A-11%7D%2C%22opensea%22%3A%7B%22fx%22%3A154%2C%22fy%22%3A-17%7D%2C%22connext%22%3A%7B%22fx%22%3A-170%2C%22fy%22%3A41%7D%2C%220x3CBd0eeCf0DdCA602AbC6516951E96136B99ca04%22%3A%7B%22fx%22%3A6%2C%22fy%22%3A5%7D%2C%22holographxyz%22%3A%7B%22fx%22%3A143%2C%22fy%22%3A-19%7D%2C%220x0000000000000000000000000000000000000000%22%3A%7B%22fx%22%3A134%2C%22fy%22%3A-22%7D%2C%220x405421Cd0b6C2Fca7A26B2af70F9B68695a9cE56%22%3A%7B%22fx%22%3A144%2C%22fy%22%3A-23%7D%2C%22borderless-bitcoin%22%3A%7B%22fx%22%3A139%2C%22fy%22%3A-19%7D%2C%220xa54c3522bca94299b852F227c5630D1657FeCD71%22%3A%7B%22fx%22%3A143%2C%22fy%22%3A-20%7D%2C%220x93e9F88dc1CB99A30caa39233a661a2739c0CCcE%22%3A%7B%22fx%22%3A151%2C%22fy%22%3A-12%7D%2C%220x3642E77cc1Fabd0399aE20fD0F49b196b0855bF3%22%3A%7B%22fx%22%3A11%2C%22fy%22%3A-32%7D%2C%220x989cbD3534860166301Bb6e56c5d5fc40B4bDa45%22%3A%7B%22fx%22%3A13%2C%22fy%22%3A60%7D%2C%220x6E91050Cf96D700545cF1b21Ab49005efb3Ab45B%22%3A%7B%22fx%22%3A11%2C%22fy%22%3A88%7D%2C%220xE9505bC513d3E07F6BB0E932250F373921C12366%22%3A%7B%22fx%22%3A13%2C%22fy%22%3A-71%7D%2C%220xE2163435824eF43546E308b617130463494e4D61%22%3A%7B%22fx%22%3A12%2C%22fy%22%3A19%7D%2C%220xFF04820c36759C9F5203021fe051239aD2dcca8a%22%3A%7B%22fx%22%3A152%2C%22fy%22%3A0%7D%2C%220x50eC4Ea76B2729F89754368c49B29132159BD207%22%3A%7B%22fx%22%3A142%2C%22fy%22%3A-3%7D%2C%220x679916d018663907E4F1b981c2826f8E8934be97%22%3A%7B%22fx%22%3A-103%2C%22fy%22%3A-27%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

https://platform.arkhamintelligence.com/visualizer/entity/0x679916d018663907E4F1b981c2826f8E8934be97,0x0cA2302aFFebdDba4f42d3d7c47089B2C73Bd6D7,0x5F21973f8FF9fbBc624963e45b6b58ed36b36245,0x037e154DD747790830fD772681044a71671E0Db1,0xD29b8FE7E0dE10D15B2554F7CF81e48A86AF520a,0xBEae689b7bDf89D140163263cA490c95FE778D11,0x2120E8AA77916ce90d08FA8C7b1Ce6C8079349e4,0xC6A0Ea88A426AA3bacf802A5cD076487516e1e10,0xD48057532910A0DA53A27204E2AFb96c82F2Ce74?flow=all&from=connext&positions=%7B%22bybit%22%3A%7B%22fx%22%3A-123%2C%22fy%22%3A-24%7D%2C%22disperse-app%22%3A%7B%22fx%22%3A146%2C%22fy%22%3A43%7D%2C%22layerzero%22%3A%7B%22fx%22%3A139%2C%22fy%22%3A51%7D%2C%22connext%22%3A%7B%22fx%22%3A-155%2C%22fy%22%3A-34%7D%2C%220x62331F1D2e5a3802aB6a58c1faB19b01edE94abd%22%3A%7B%22fx%22%3A127%2C%22fy%22%3A26%7D%2C%220x39b55965Dfe22Da420F8c73D564364ec480EB3C8%22%3A%7B%22fx%22%3A108%2C%22fy%22%3A-47%7D%2C%22uniswap%22%3A%7B%22fx%22%3A143%2C%22fy%22%3A38%7D%2C%22hop-protocol%22%3A%7B%22fx%22%3A142%2C%22fy%22%3A29%7D%2C%22trader-joe%22%3A%7B%22fx%22%3A155%2C%22fy%22%3A1%7D%2C%22space-id%22%3A%7B%22fx%22%3A144%2C%22fy%22%3A-19%7D%2C%220xD29b8FE7E0dE10D15B2554F7CF81e48A86AF520a%22%3A%7B%22fx%22%3A29%2C%22fy%22%3A-46%7D%2C%220x5F21973f8FF9fbBc624963e45b6b58ed36b36245%22%3A%7B%22fx%22%3A32%2C%22fy%22%3A-27%7D%2C%220x679916d018663907E4F1b981c2826f8E8934be97%22%3A%7B%22fx%22%3A32%2C%22fy%22%3A-13%7D%2C%220x0cA2302aFFebdDba4f42d3d7c47089B2C73Bd6D7%22%3A%7B%22fx%22%3A28%2C%22fy%22%3A31%7D%2C%220x037e154DD747790830fD772681044a71671E0Db1%22%3A%7B%22fx%22%3A25%2C%22fy%22%3A12%7D%2C%220x2120E8AA77916ce90d08FA8C7b1Ce6C8079349e4%22%3A%7B%22fx%22%3A61%2C%22fy%22%3A27%7D%2C%220xBEae689b7bDf89D140163263cA490c95FE778D11%22%3A%7B%22fx%22%3A21%2C%22fy%22%3A69%7D%2C%220xD48057532910A0DA53A27204E2AFb96c82F2Ce74%22%3A%7B%22fx%22%3A48%2C%22fy%22%3A-55%7D%2C%220xC6A0Ea88A426AA3bacf802A5cD076487516e1e10%22%3A%7B%22fx%22%3A83%2C%22fy%22%3A-3%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

# Rewards Address

0xe8628a9f7727bcefeab492d601de0a0fb1ab07fc

**Comment by ronaskin** [comment] 2023-08-29 10:23
![Screenshot_10](https://github.com/connext/community-sybil-reports/assets/137379395/8e289631-fe13-4f47-ad24-ac65c749bc46)

**Comment by vi11am12** [comment] 2023-09-01 13:19
All addresses are present in my submission here: #6

**Comment by ArjunBhuptani** [comment] 2023-09-01 15:01
Duplicate of #6 which was first

**Closed by ArjunBhuptani** 2023-09-01 15:01 UTC
Labels: duplicate
