### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by eddingo345** [connext/community-sybil-reports#82] opened 2023-08-25 07:57 UTC
# Related Addresses
```
0xaac2f9d9d26c7cdd9b8d2cca67a08323e525f641
0xd08267ce370be8074fca61f2ee855c78b0ab910d
0x9542495bbe11840eb64287f73ac78da61c837714
0xec911027c5956c4b7e3b79b06c0d107b3a003f1f
0xc2b1faa0a2615c6e315596dc6cbe3c1049c0aa0f
0x503d17563769a941f9c877966790c389053f79a1
0x1ea05e66559c497b7d786a3f657baa5ba7fe0bc3
0x0a26c375ee357dfb67441871ddec53f57ffe6d65
0x71254be0af9f5522425c75a2dd1c0fc42162655f
0xe6d36da02583c1acd79ffc7065f6d9bb1e8a6c30
0x552f386a3c6fda19eb75acde84f013df69a7006e
0x53716f7ff7949e06afaeed5aa169ca31e53d7d46
0xa2d8425a38fad12058519c0d334d89172ae42d2c
0xdfe9e837a7bc21b0c928066e471e542ff75d3831
0x470169600e08c6733cbafeeedef1352f4738b0c7
0xc218e61c2f6ede9bfdb504f85bdf8802cbece31a
0x2c382dae1a94d689becf78edbeb1900c46f75ca2
0x63ea96398ffcac3b4bede15de824468328e3bc45
0xf0a9da8cc27830d4a7cc9da49a18655371653321
0x1d9d739004473c231cd08111bb5dd5e7c082dcd4
0x5df9576b0c6441f69809ca510685c01f09dba1e9
0x1690c3435802ca8482f76ecfc32158b345057649
0x0715b21a1f43c80ce41dacb7e1ea89aa8fe3fc2a
0x00493ba4e1864acd75e2d76d7b6f4e6593615631
0xb18af22479f14f26487aa6354dad7d7cbcd527f1
0x3d4f2f2feb4963bdcc0cd48d6e2b57806c3f2ff3
0xcb8189bcf385867db54e72c390472d646a448003
0x1f27f86dbb71f47222ccb50f8a19ace82cdf29b4
0xc5263403c4b068e0efafa3463e08e40f8ade391c
```

# Reasoning

All addresses has LP position in Arbi USDT LP. 13.6k$
All of them are conencted with TXs. you can see them here 
https://platform.arkhamintelligence.com/visualizer/entity/0xaac2F9d9D26c7CDD9b8d2cca67a08323E525F641,0xD08267cE370BE8074FcA61f2ee855C78b0AB910D,0x9542495bBE11840eB64287f73aC78DA61C837714,0xec911027C5956C4B7e3b79B06c0D107b3a003F1F,0xC2B1FAA0a2615C6e315596dc6CbE3c1049C0aA0F,0x503d17563769a941f9c877966790C389053F79A1,0x1eA05E66559c497b7d786a3F657BaA5ba7FE0Bc3,0x0A26c375EE357dfB67441871dDec53f57FFE6d65,0x71254Be0AF9f5522425C75A2dD1C0fC42162655F,0xE6d36Da02583C1acD79FFC7065f6d9BB1e8a6C30,0xE6d36Da02583C1acD79FFC7065f6d9BB1e8a6C30,0x53716f7fF7949e06AfaEED5aA169cA31E53d7d46,0xA2D8425A38fAD12058519c0d334d89172AE42D2c,0xDfE9e837A7BC21b0c928066e471E542fF75d3831,0x470169600E08c6733cBAfeeEdeF1352f4738B0C7,0xC218E61C2f6EDe9bfdb504f85BDf8802CBEce31A,0x2C382DAe1a94D689BEcf78eDBEB1900C46f75ca2,0x63ea96398ffCaC3b4BEdE15DE824468328E3BC45,0xF0a9dA8cc27830D4a7Cc9Da49a18655371653321,0x1d9D739004473c231cd08111bB5dd5E7c082dCd4,0x5dF9576b0C6441F69809Ca510685C01F09DbA1e9,0x1690C3435802CA8482F76ecFc32158b345057649,0x0715B21A1f43C80CE41daCb7E1Ea89Aa8fe3FC2A,0x00493ba4E1864aCd75e2d76D7B6F4E6593615631,0xB18Af22479F14F26487Aa6354dAD7D7CBcd527F1,0x3d4f2F2feb4963BdCC0cd48d6e2B57806c3F2ff3,0xCB8189bcF385867Db54E72c390472D646A448003,0x1f27F86dBB71F47222ccb50F8A19acE82cDf29b4,0xc5263403C4B068e0efaFa3463e08e40F8aDe391C?flow=all&positions=%7B%220xC218E61C2f6EDe9bfdb504f85BDf8802CBEce31A%22%3A%7B%22fx%22%3A70%2C%22fy%22%3A-30%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

# Methodology

I have used arkham service to find connections

Same LP ammount-pretty sus. same TXs among stargate/1inch etc

https://dune.com/KARTOD/connext-bridge-activity-and-top-30percent-depositors
https://platform.arkhamintelligence.com/
https://platform.arkhamintelligence.com/visualizer/entity/0xaac2F9d9D26c7CDD9b8d2cca67a08323E525F641,0xD08267cE370BE8074FcA61f2ee855C78b0AB910D,0x9542495bBE11840eB64287f73aC78DA61C837714,0xec911027C5956C4B7e3b79B06c0D107b3a003F1F,0xC2B1FAA0a2615C6e315596dc6CbE3c1049C0aA0F,0x503d17563769a941f9c877966790C389053F79A1,0x1eA05E66559c497b7d786a3F657BaA5ba7FE0Bc3,0x0A26c375EE357dfB67441871dDec53f57FFE6d65,0x71254Be0AF9f5522425C75A2dD1C0fC42162655F,0xE6d36Da02583C1acD79FFC7065f6d9BB1e8a6C30,0xE6d36Da02583C1acD79FFC7065f6d9BB1e8a6C30,0x53716f7fF7949e06AfaEED5aA169cA31E53d7d46,0xA2D8425A38fAD12058519c0d334d89172AE42D2c,0xDfE9e837A7BC21b0c928066e471E542fF75d3831,0x470169600E08c6733cBAfeeEdeF1352f4738B0C7,0xC218E61C2f6EDe9bfdb504f85BDf8802CBEce31A,0x2C382DAe1a94D689BEcf78eDBEB1900C46f75ca2,0x63ea96398ffCaC3b4BEdE15DE824468328E3BC45,0xF0a9dA8cc27830D4a7Cc9Da49a18655371653321,0x1d9D739004473c231cd08111bB5dd5E7c082dCd4,0x5dF9576b0C6441F69809Ca510685C01F09DbA1e9,0x1690C3435802CA8482F76ecFc32158b345057649,0x0715B21A1f43C80CE41daCb7E1Ea89Aa8fe3FC2A,0x00493ba4E1864aCd75e2d76D7B6F4E6593615631,0xB18Af22479F14F26487Aa6354dAD7D7CBcd527F1,0x3d4f2F2feb4963BdCC0cd48d6e2B57806c3F2ff3,0xCB8189bcF385867Db54E72c390472D646A448003,0x1f27F86dBB71F47222ccb50F8A19acE82cDf29b4,0xc5263403C4B068e0efaFa3463e08e40F8aDe391C?flow=all&positions=%7B%220xC218E61C2f6EDe9bfdb504f85BDf8802CBEce31A%22%3A%7B%22fx%22%3A70%2C%22fy%22%3A-30%7D%7D&sortDir=desc&sortKey=time&usdGte=0.1

# Rewards Address

0xc1f8C37dDFFFa7a565D300613c5444AA2Acd152a

**Comment by ArjunBhuptani** [comment] 2023-09-01 01:20
Duplicate of #12

**Closed by ArjunBhuptani** 2023-09-01 01:20 UTC
Labels: duplicate
