### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by devstude** [connext/community-sybil-reports#409] opened 2023-08-26 20:13 UTC
# Related Addresses
0xabaac6fa8f3d4f217da671cad2426da7cdeecbba
0x1c37a6c236c0d8db331b9e4c4f6388484c908c5a
0xacacfdd0cc95e2283adfa0038ce47d44d7c8a65b
0x3ec1bef9d3dc58ef260e3774e1db4486f20cce56
0x41562e15757a4648ac5de3b50a9989b7ac3e59c3
0x53b67a0730ab783b91afcb12a9d8baa54b50055a
0xbfaa11fc64bce2ee29ab2ed781283e064f2f219c
0x097e3601a93862cf099162e86a2a8af9d42643e3
0xe0a209b28ce5467b84e1c0cc3427463c96eb0536
0x2c764dfb65525633a2b372a257fb6532ba91dae4

# Reasoning

All addresses where initially funded on BNB Chain from same main account 0xc4c31ea0ee79b251bc7dc469969232f084748920 (which is not eligible for the Connext airdrop) with the same amount of 0,01 bnb at the same day 2020-12-24: owner spent just 3 minutes to spread funds on all those accounts.

Initial funding of those wallets where made in a batch of funding of 50 bnb chain wallets for sybiling. But only those 10 of them are eligible for the Connext airdrop. You can see those transactions here:
https://bscscan.com/txs?a=0xc4c31ea0ee79b251bc7dc469969232f084748920&p=1
https://bscscan.com/txs?a=0xc4c31ea0ee79b251bc7dc469969232f084748920&p=2

# Methodology

Those accounts where found by running dune scripts that analyze initial wallet fundings (for wallets eligible for the Connext user airdrop) and manual checking of same time/value/initial funder wallets. 

# Rewards Address

0xEd3aAD546d663084794CcCcA6987089395FC1760

**Comment by A-Keyboard** [comment] 2023-09-02 00:21
duplicate of https://github.com/connext/community-sybil-reports/issues/217

**Comment by A-Keyboard** [comment] 2023-09-02 15:00
not a duplicate, fixed

**Closed** 2023-09-02 20:18 UTC
Labels: pending application, ts
