### ISSUE TITLE
Sybil Report

### ISSUE THREAD

**Issue by seeeath** [connext/community-sybil-reports#340] opened 2023-08-26 07:42 UTC
0xa62a736eacc859c25d80a59b09fc1d22bb04c478
0xb6a76ec08b4718a254c36ab074028dbf5ad98bd9
0xf3c17debd41a7961cf152c5c365c8bde1f2a5e04
0xccbde2f30fe5180f5fc9b3f66560f5b08b47e808
0x6f6e19c4102198b8214f684443bf18da137a596b
0x15f74ad03d4dd41d7f38dbddcecd62351e716564
0xe745affb1c0906562d7b35deb241fcec6f3c8a71
0x308bff19af12fd521bd5f35ffa42bd1d9b4eb97a
0x2b54dea43c078fbb20f6fa1b62cb222eea0ff301
0x90a7aa87b4856a7ce6eaa1a236cd5e4507a85d76
0xbf03f7b37ca80c0c05db9bc747541a278fb7cbcc
0x660b6989b901a2febbebdba8cddceec8955b9fcc
0x95738b5509272452610333ccc9e89460a026e1df
0x83d553362dfc0c1295e98f879edc98d54a8d8854

**Reasons why all of one person's wallets**

1. Same time to create a wallet (711 and 710 days mostly, one 725 days)
2. Identical first and subsequent transactions 
3. Transfers between each other of all wallets that were in the list (scroll an account - transfer to another and so on round and round)
4. Identical zero balance of wallets
5. Identical zero activity on wallets after scrolling tasks for retrodrops
6.  Almost every wallet last trasaction made a deposit to one OKX wallet 0x099e339814766b8e66ebb10ad1f53c947485172f

**1.**
1. Same time to create a wallet (711 and 710 days mostly, one 725 days)
![days](https://github.com/connext/community-sybil-reports/assets/38422073/285ce67c-8b4e-4b8d-9a89-5b3ed5719d88)

**2 and 3**
2. Identical first and subsequent transactions and transfers between each other of all wallets that were in the list
![first](https://github.com/connext/community-sybil-reports/assets/38422073/9938499e-47be-413c-822d-b2cfa0340a27)
![two](https://github.com/connext/community-sybil-reports/assets/38422073/7ead82b2-a7d6-4716-aad3-aa4ef8a52806)

**4 and 5**
3. Identical zero balance of wallets and identical zero activity on wallets after scrolling tasks for retrodrops

I'll just leave the debunking links. You can see that a person topped up one wallet then made activity in it on projects and transferred to the next, without leaving a 10 dollars on the account. Transactions are identical.

[0xa62a736eacc859c25d80a59b09fc1d22bb04c478 debank](https://debank.com/profile/0xa62a736eacc859c25d80a59b09fc1d22bb04c478/history)
[0xb6a76ec08b4718a254c36ab074028dbf5ad98bd9 debank](https://debank.com/profile/0xb6a76ec08b4718a254c36ab074028dbf5ad98bd9/history)
[0xf3c17debd41a7961cf152c5c365c8bde1f2a5e04 debank
](https://debank.com/profile/0xf3c17debd41a7961cf152c5c365c8bde1f2a5e04/history)[0xccbde2f30fe5180f5fc9b3f66560f5b08b47e808 debank](https://debank.com/profile/0xccbde2f30fe5180f5fc9b3f66560f5b08b47e808/history)
[0x6f6e19c4102198b8214f684443bf18da137a596b debank](https://debank.com/profile/0x6f6e19c4102198b8214f684443bf18da137a596b/history)
[0x15f74ad03d4dd41d7f38dbddcecd62351e716564 debank](https://debank.com/profile/0x15f74ad03d4dd41d7f38dbddcecd62351e716564/history)
[0xe745affb1c0906562d7b35deb241fcec6f3c8a71 debank](https://debank.com/profile/0xe745affb1c0906562d7b35deb241fcec6f3c8a71/history)
[0x308bff19af12fd521bd5f35ffa42bd1d9b4eb97a debank
](https://debank.com/profile/0x308bff19af12fd521bd5f35ffa42bd1d9b4eb97a/history)[0x2b54dea43c078fbb20f6fa1b62cb222eea0ff301 debank](https://debank.com/profile/0x2b54dea43c078fbb20f6fa1b62cb222eea0ff301/history)
[0x90a7aa87b4856a7ce6eaa1a236cd5e4507a85d76 debank](https://debank.com/profile/0x90a7aa87b4856a7ce6eaa1a236cd5e4507a85d76/history)
[0xbf03f7b37ca80c0c05db9bc747541a278fb7cbcc debank](https://debank.com/profile/0xbf03f7b37ca80c0c05db9bc747541a278fb7cbcc/history)
[0x660b6989b901a2febbebdba8cddceec8955b9fcc debank](https://debank.com/profile/0x660b6989b901a2febbebdba8cddceec8955b9fcc/history)
[0x95738b5509272452610333ccc9e89460a026e1df debank](https://debank.com/profile/0x95738b5509272452610333ccc9e89460a026e1df/history)
[0x83d553362dfc0c1295e98f879edc98d54a8d8854 debank](https://debank.com/profile/0x83d553362dfc0c1295e98f879edc98d54a8d8854/history)

**6.**  
6. Almost every wallet last trasaction made a deposit to one OKX wallet 0x099e339814766b8e66ebb10ad1f53c947485172f

https://polygonscan.com/tx/0x07240ebbda8b7f0ff681a4a658629e5d3b5021a0141d7ecd95293ebe12256609
https://polygonscan.com/tx/0x5796c6f59c7fe1b776766da1a8d2634801e6759960e7789e839963f987ce7062
https://polygonscan.com/tx/0x6c81429a86d46ad7262c06f99ffada0c77cb33e3938c81646c8ec6aa5d82d322
https://polygonscan.com/tx/0x45462656fae619cbfcfec61141981f1737073ea26aa36af06f73f968198c05f9
https://polygonscan.com/tx/0x3b31ae5e873a4edffa5c8c7acd155006e6ce94336a0ebbf1925eee94883a10ab
https://polygonscan.com/tx/0xd78a39fc7fe189a954fc735cfe4edcc78c8e8e3e2e73d04ab1bb40177958a1f2
https://polygonscan.com/tx/0x7601f48f59f5e3ac9ade886a9af1dd31673cff17c1e34cb17c5fc45b004d9cba
https://polygonscan.com/tx/0xab788b92453386c5b2bcb9c207e4297b8fbe7b526b0bacdd2bc0ebc5998d33d9
https://polygonscan.com/tx/0x2e60e375079456fe29e53a78db77e95b16a67831777043cce8745009a435f7a4
https://polygonscan.com/tx/0xbcca425ad7d4a692672d69d88bcf2badeccba2e7d94de9bf8079413f0c7752d0
https://polygonscan.com/tx/0x8906097fea7bb3365adb1690c57795fbe8612fdf648e7c1da24c6a6fc987fb61

_By method - I took those wallets that can get the drop. Then I looked at the number of transactions, date of creation. So I used this multiaccessor to open the wallet I was transferring to for the first identical transactions, see if it was suitable for the drop, and then look for a similar one._

# Rewards Address

0x99A44EBF80Eb3dd3a4EF8a43A795d12A196a65b4

**Comment by prathmeshkhandelwal1** [comment] 2023-09-01 12:12
Address have interactions with each other too and fro. Confirmed via arkham.
https://platform.arkhamintelligence.com/visualizer/entity/0xa62A736EacC859c25D80a59b09FC1D22bb04c478,0xb6A76Ec08b4718A254c36Ab074028DbF5ad98Bd9,0xf3C17Debd41A7961cF152c5C365C8BDe1f2a5e04,0xCcbde2F30FE5180f5fc9B3f66560F5B08B47e808,0x6f6E19C4102198B8214F684443bF18dA137a596B,0x15f74aD03d4Dd41d7f38DbddCECd62351E716564,0xE745aFFB1c0906562D7b35DEB241fCeC6F3C8a71,0x308bff19aF12fD521bd5F35FFa42bD1d9b4eb97a,0x2b54dEa43c078fbB20F6FA1b62CB222EeA0Ff301,0x90A7aA87B4856a7CE6EAA1a236CD5e4507A85D76,0xbF03f7b37cA80c0c05dB9Bc747541A278Fb7cBcc,0x660B6989B901A2FebbEBdBA8cdDCEEc8955b9fcc,0x95738B5509272452610333ccc9E89460a026E1DF,0x83D553362Dfc0c1295e98f879EDc98D54a8D8854?flow=all&positions=%7B%7D&sortDir=desc&sortKey=time&usdGte=0.1

**Comment by A-Keyboard** [comment] 2023-09-02 02:44
Duplicate of https://github.com/connext/community-sybil-reports/issues/246

**Closed** 2023-09-03 15:38 UTC
Labels: duplicate
